using System; using System.Collections.Generic; using System.Linq; using System.Threading; using System.Threading.Tasks; using LicenseScope.Core.Contracts; using LicenseScope.Core.Models; using LicenseScope.Adobe.Classification; using LicenseScope.Adobe.Contracts; using LicenseScope.Adobe.Detection; using LicenseScope.Adobe.Models;
namespace LicenseScope.Adobe
{
 public sealed class AdobeLicenseScanner:ILicenseScanner
 {
  readonly IAdobeInstallationDetector detector;readonly IAdobeLicensingEvidenceProvider evidence;readonly IAdobeSharedDeviceConfigurationDetector shared;readonly IAdobeServiceStatusProvider service;readonly ISystemClock clock;public AdobeLicenseScanner(IAdobeInstallationDetector d,IAdobeLicensingEvidenceProvider e,IAdobeSharedDeviceConfigurationDetector c,IAdobeServiceStatusProvider s,ISystemClock k){detector=d;evidence=e;shared=c;service=s;clock=k;}
  public string ScannerId=>"adobe.desktop";public string VendorName=>"Adobe";public bool IsApplicable(SystemContext context)=>context!=null&&(context.OsName.IndexOf("Windows",StringComparison.OrdinalIgnoreCase)>=0||!string.IsNullOrWhiteSpace(context.WindowsDirectory));
  public async Task<IReadOnlyList<LicenseResult>> ScanAsync(SystemContext context,CancellationToken token){token.ThrowIfCancellationRequested();var products=detector.Detect(context,out var detectionWarnings);token.ThrowIfCancellationRequested();var config=shared.Detect();token.ThrowIfCancellationRequested();var services=service.GetStatus();token.ThrowIfCancellationRequested();var licenses=await evidence.ReadLicenseInformationAsync(token).ConfigureAwait(false);var results=new List<LicenseResult>();var matched=new HashSet<AdobeInstalledProduct>();var common=detectionWarnings.Concat(licenses.Warnings).Concat(string.IsNullOrWhiteSpace(config.Warning)?Array.Empty<string>():new[]{config.Warning}).Concat(string.IsNullOrWhiteSpace(services.Warning)?Array.Empty<string>():new[]{services.Warning}).ToArray();
   foreach(var license in licenses.Records){token.ThrowIfCancellationRequested();var product=AdobeProductMatcher.Match(license,products);if(product==null)continue;matched.Add(product);results.Add(Create(product,license,config,services,common));}foreach(var product in products.Where(x=>!matched.Contains(x))){token.ThrowIfCancellationRequested();results.Add(Create(product,null,config,services,common));}return results.OrderBy(x=>x.ProductName,StringComparer.OrdinalIgnoreCase).ThenBy(x=>x.ProductVersion,StringComparer.OrdinalIgnoreCase).ToArray();}
  LicenseResult Create(AdobeInstalledProduct product,AdobeLicenseRecord license,AdobeSharedDeviceConfiguration config,AdobeServiceStatus serviceStatus,IReadOnlyList<string> inherited){var warnings=new List<string>(inherited);var model=license==null?"NamedUser":AdobeLicenseClassifier.Model(license.DeploymentMode);var status=license==null?LicenseStatus.NeedsOnlineVerification:AdobeLicenseClassifier.Status(license,clock.UtcNow);if(license==null)warnings.Add("Installed Adobe application has no matching trusted toolkit license record; online verification is required.");if(model=="NamedUser"||model=="NamedUserEducationLab")warnings.Add("User sign-in and current Adobe entitlement may still be required.");if(config.Present&&license==null)warnings.Add("Shared Device configuration is present but does not prove a current license.");if(license!=null&&license.CacheExpiry.HasValue&&license.CacheExpiry.Value<=clock.UtcNow&&license.LicenseExpiry.HasValue&&license.LicenseExpiry.Value>clock.UtcNow){status=LicenseStatus.NeedsOnlineVerification;warnings.Add("Local cache expiry has passed; online verification is required.");}var facts=new List<ScanEvidence>{new ScanEvidence{Source=product.DetectionSource,Name="Installation",Value="Observed",Confidence=ConfidenceLevel.Medium},new ScanEvidence{Source="Adobe Shared Device configuration",Name="Configuration present",Value=config.Present?"Yes":"No",Confidence=ConfidenceLevel.Low},new ScanEvidence{Source="Windows Service Control Manager",Name="Adobe Genuine Service",Value=!serviceStatus.Found?"Not found":serviceStatus.Running?"Running":"Not running",Confidence=ConfidenceLevel.Low}};if(config.Present)facts.Add(new ScanEvidence{Source="Adobe OperatingConfigs directory",Name="Configuration count",Value=config.Count.ToString(),Confidence=ConfidenceLevel.Low});if(license!=null){facts.Add(new ScanEvidence{Source="Adobe Licensing Toolkit license information",Name="Deployment mode",Value=model,Confidence=ConfidenceLevel.High});if(license.LicenseExpiry.HasValue)facts.Add(new ScanEvidence{Source="Adobe Licensing Toolkit license information",Name="License expiry",Value=license.LicenseExpiry.Value.ToString("O"),Confidence=ConfidenceLevel.High});if(license.CacheExpiry.HasValue)facts.Add(new ScanEvidence{Source="Adobe Licensing Toolkit license information",Name="Cache expiry",Value=license.CacheExpiry.Value.ToString("O"),Confidence=ConfidenceLevel.Medium});}
   return new LicenseResult{ScannerId=ScannerId,Vendor=VendorName,ProductName=product.ProductName,ProductVersion=product.Version,Installed=true,Status=status,IsLicensed=status==LicenseStatus.Licensed?true:status==LicenseStatus.Expired?false:(bool?)null,LicenseType=model,Confidence=license==null?ConfidenceLevel.Low:ConfidenceLevel.High,ExpirationDate=license?.LicenseExpiry,Evidence=facts,Warnings=warnings.Distinct().ToArray()};}
 }
}
