using System;using System.Collections.Generic;using System.IO;using Microsoft.Win32;using WinLic.Core.Models;using WinLic.Scanners.SketchUp.Contracts;using WinLic.Scanners.SketchUp.Models;
namespace WinLic.Scanners.SketchUp.Detection
{
 public sealed class SketchUpInstallationDetector:ISketchUpInstallationDetector
 {
  static readonly string[] Excluded={"Viewer","Importer","SDK","Language Pack","LayOut","Style Builder","Extension Warehouse","Trimble Connect","Installer","Updater","Crash","V-Ray","Enscape"};
  public IReadOnlyList<SketchUpInstalledProduct>Detect(SystemContext context,out IReadOnlyList<string>warnings){var map=new Dictionary<string,SketchUpInstalledProduct>(StringComparer.OrdinalIgnoreCase);var notes=new List<string>();Read(RegistryView.Registry32,map,notes);if(Environment.Is64BitOperatingSystem)Read(RegistryView.Registry64,map,notes);var result=new List<SketchUpInstalledProduct>(map.Values);result.Sort((a,b)=>string.Compare(a.ReleaseYear+a.Version,b.ReleaseYear+b.Version,StringComparison.OrdinalIgnoreCase));warnings=notes;return result;}
  public static bool IsProduct(string publisher,string name){if(name.IndexOf("SketchUp",StringComparison.OrdinalIgnoreCase)<0||publisher.IndexOf("SketchUp",StringComparison.OrdinalIgnoreCase)<0&&publisher.IndexOf("Trimble",StringComparison.OrdinalIgnoreCase)<0)return false;foreach(var x in Excluded)if(name.IndexOf(x,StringComparison.OrdinalIgnoreCase)>=0)return false;return true;}
  static void Read(RegistryView view,IDictionary<string,SketchUpInstalledProduct>map,ICollection<string>notes){try{using(var hive=RegistryKey.OpenBaseKey(RegistryHive.LocalMachine,view))using(var root=hive.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",false)){if(root==null)return;foreach(var id in root.GetSubKeyNames())using(var key=root.OpenSubKey(id,false)){var name=key?.GetValue("DisplayName") as string??"";var publisher=key?.GetValue("Publisher") as string??"";if(!IsProduct(publisher,name))continue;var version=key?.GetValue("DisplayVersion") as string??"";var year=Year(name,version);var location=key?.GetValue("InstallLocation") as string??"";map[year+"|"+version]=new SketchUpInstalledProduct{ProductName=string.IsNullOrWhiteSpace(year)?"SketchUp Desktop":"SketchUp Pro "+year,Version=version,ReleaseYear=year,Architecture=view==RegistryView.Registry64?"x64":"x86",InstallLocation=location,DetectionSource="Registry uninstall metadata ("+view+")",LayOutInstalled=SafeExists(Path.Combine(location,"LayOut")),StyleBuilderInstalled=SafeExists(Path.Combine(location,"Style Builder"))};}}}catch(Exception ex)when(ex is UnauthorizedAccessException||ex is System.Security.SecurityException||ex is IOException){notes.Add("SketchUp installation metadata unavailable: "+ex.GetType().Name);}}
  static string Year(string name,string version){for(var y=2026;y>=2017;y--)if(name.IndexOf(y.ToString(),StringComparison.Ordinal)>=0)return y.ToString();return version.Length>=4&&int.TryParse(version.Substring(0,4),out var parsedYear)&&parsedYear>=2017&&parsedYear<=2026?parsedYear.ToString():"";}static bool SafeExists(string path){try{return !string.IsNullOrWhiteSpace(path)&&Directory.Exists(path);}catch(Exception ex)when(ex is UnauthorizedAccessException||ex is IOException){return false;}}
 }
}
