using System; using Microsoft.VisualStudio.TestTools.UnitTesting; using WinLic.Compatibility;
namespace WinLic.Compatibility.Tests {
[TestClass] public class ArchitectureTests {
[DataTestMethod][DataRow((ushort)0x014c,CpuArchitecture.X86)][DataRow((ushort)0x8664,CpuArchitecture.X64)][DataRow((ushort)0xaa64,CpuArchitecture.Arm64)][DataRow((ushort)0xffff,CpuArchitecture.Unknown)] public void MachineCodesMap(ushort m,CpuArchitecture e)=>Assert.AreEqual(e,WindowsArchitectureProbe.Map(m));
[DataTestMethod][DataRow(CpuArchitecture.X86,CpuArchitecture.X86,ProcessExecutionMode.NativeX86)][DataRow(CpuArchitecture.X64,CpuArchitecture.X64,ProcessExecutionMode.NativeX64)][DataRow(CpuArchitecture.Arm64,CpuArchitecture.Arm64,ProcessExecutionMode.NativeArm64)][DataRow(CpuArchitecture.X86,CpuArchitecture.X64,ProcessExecutionMode.X86OnX64)][DataRow(CpuArchitecture.X86,CpuArchitecture.Arm64,ProcessExecutionMode.X86OnArm64)][DataRow(CpuArchitecture.X64,CpuArchitecture.Arm64,ProcessExecutionMode.X64OnArm64)] public void Modes(CpuArchitecture p,CpuArchitecture n,ProcessExecutionMode e)=>Assert.AreEqual(e,WindowsArchitectureProbe.Create(p,n).ExecutionMode);
[TestMethod]public void ArmEmulation()=>Assert.IsTrue(WindowsArchitectureProbe.Create(CpuArchitecture.X64,CpuArchitecture.Arm64).IsEmulated); [TestMethod]public void Wow64NotArm()=>Assert.IsFalse(WindowsArchitectureProbe.Create(CpuArchitecture.X86,CpuArchitecture.X64).IsEmulated); }
[TestClass] public class FrameworkTests { [DataTestMethod][DataRow(528040,4,8,0)][DataRow(528049,4,8,0)][DataRow(533320,4,8,1)][DataRow(600000,4,8,1)] public void Maps(int r,int a,int b,int c)=>Assert.AreEqual(new Version(a,b,c),NetFrameworkReleaseMapper.Map(r)); [TestMethod]public void Missing()=>Assert.AreEqual(new Version(0,0),NetFrameworkReleaseMapper.Map(null)); [TestMethod]public void Old()=>Assert.AreEqual(new Version(0,0),NetFrameworkReleaseMapper.Map(461814)); }
[TestClass] public class EvaluatorTests { static RuntimeEnvironmentInfo E(int m,int b,CpuArchitecture n=CpuArchitecture.X64)=>new RuntimeEnvironmentInfo{WindowsVersion=new Version(m==10?10:6,m==10?0:m,b),NativeOsArchitecture=n,ProcessArchitecture=CpuArchitecture.X64,InstalledNetFrameworkVersion=new Version(4,8)}; static PayloadDescriptor P(CpuArchitecture a=CpuArchitecture.X64)=>new PayloadDescriptor{Id=a==CpuArchitecture.X86?"winlic-net48-x86":"winlic-net48-x64",TargetFramework="net48",ProcessArchitecture=a,RequiredFrameworkVersion=new Version(4,8)};
[TestMethod]public void Win7(){var r=new CompatibilityEvaluator().Evaluate(E(1,7601),P());Assert.IsTrue(r.CanRunAudit);Assert.IsTrue(r.IsEndOfLife);}[TestMethod]public void Win8()=>Assert.IsFalse(new CompatibilityEvaluator().Evaluate(E(2,9200),P()).CanStart);[TestMethod]public void Win81()=>Assert.IsTrue(new CompatibilityEvaluator().Evaluate(E(3,9600),P()).CanRunAudit);[TestMethod]public void Win10Eol()=>Assert.IsTrue(new CompatibilityEvaluator().Evaluate(E(10,19045),P()).IsEndOfLife);[TestMethod]public void Win11()=>Assert.IsTrue(new CompatibilityEvaluator().Evaluate(E(10,22631),P()).CanRunAudit);
[TestMethod]public void Framework(){var e=E(10,22631);e.InstalledNetFrameworkVersion=new Version(4,7,2);Assert.IsFalse(new CompatibilityEvaluator().Evaluate(e,P()).CanStart);}[TestMethod]public void X64OnX86()=>Assert.IsFalse(new CompatibilityEvaluator().Evaluate(E(10,19045,CpuArchitecture.X86),P()).CanStart);[TestMethod]public void X86OnX64()=>Assert.IsTrue(new CompatibilityEvaluator().Evaluate(E(10,19045),P(CpuArchitecture.X86)).CanRunAudit);[TestMethod]public void Win10ArmX86()=>Assert.AreEqual("winlic-net48-x86",new CompatibilityEvaluator().Evaluate(E(10,19045,CpuArchitecture.Arm64),P(CpuArchitecture.X86)).RecommendedPayloadId);[TestMethod]public void Win10ArmX64()=>Assert.IsFalse(new CompatibilityEvaluator().Evaluate(E(10,19045,CpuArchitecture.Arm64),P()).CanStart);[TestMethod]public void Win11Arm()=>Assert.AreEqual("winlic-net48-x64",new CompatibilityEvaluator().Evaluate(E(10,22631,CpuArchitecture.Arm64),P()).RecommendedPayloadId);[TestMethod]public void Server(){var e=E(10,20348);e.IsWindowsServer=true;Assert.IsFalse(new CompatibilityEvaluator().Evaluate(e,P()).CanStart);}[TestMethod]public void Unknown()=>Assert.IsFalse(new CompatibilityEvaluator().Evaluate(new RuntimeEnvironmentInfo{WindowsVersion=new Version(5,1),InstalledNetFrameworkVersion=new Version(4,8)},P()).CanStart);[TestMethod]public void Emulated(){var e=E(10,22631,CpuArchitecture.Arm64);e.IsEmulated=true;Assert.AreEqual(1,new CompatibilityEvaluator().Evaluate(e,P()).Warnings.Count);} }
}
