using System;using System.Collections.Generic;using System.Linq;using System.Threading;using System.Threading.Tasks;using Microsoft.VisualStudio.TestTools.UnitTesting;using WinLic.Core.Contracts;using WinLic.Core.Models;using WinLic.Core.Runtime;using WinLic.Scanners.Adobe;using WinLic.Scanners.Adobe.Acquisition;using WinLic.Scanners.Adobe.Classification;using WinLic.Scanners.Adobe.Contracts;using WinLic.Scanners.Adobe.Detection;using WinLic.Scanners.Adobe.Models;using WinLic.Scanners.Adobe.Parsing;
namespace WinLic.Scanners.Adobe.Tests
{
 [TestClass]public class ParserTests{
  [TestMethod]public void ParsesMultipleAndDropsRawIds(){var s="Adobe Licensing Toolkit\nNpdId: SECRET-NPD\nAppId: Photoshop1\nDeploymentMode: SHARED_DEVICE\nCacheExpiry: 2027-01-01T00:00:00+00:00\nLicenseId: SECRET-LICENSE\nLicenseExpiry: 2028-01-01T00:00:00+00:00\nNpdId: SECOND\nAppId: Illustrator1\nDeploymentMode: NAMED_USER_EDUCATION_LAB\nOperation Successfully Completed";var r=new AdobeLicenseInformationParser().Parse(s);Assert.IsTrue(r.Successful);Assert.AreEqual(2,r.Records.Count);Assert.IsTrue(r.Records.All(x=>x.NpdIdPresent));Assert.IsTrue(r.Records[0].LicenseIdPresent);var text=string.Join("|",r.Records.Select(x=>x.ToString()));Assert.IsFalse(text.Contains("SECRET"));}
  [TestMethod]public void DuplicateSuppressedAndUnknownIgnored(){var s="NpdId:x\nAppId:Photoshop1\nDeploymentMode:SHARED_DEVICE\nUnknown:value\nNpdId:y\nAppId:Photoshop1\nDeploymentMode:SHARED_DEVICE";Assert.AreEqual(1,new AdobeLicenseInformationParser().Parse(s).Records.Count);}
  [TestMethod]public void AmbiguousDateNotTrusted(){var r=new AdobeLicenseInformationParser().Parse("NpdId:x\nAppId:Photoshop1\nLicenseExpiry:03/06/21 20:01:56 India Standard Time");Assert.IsNull(r.Records.Single().LicenseExpiry);Assert.IsFalse(r.Records.Single().DatesUnambiguous);}
  [TestMethod]public void CrLfUnicodeAndPartialBlock(){var r=new AdobeLicenseInformationParser().Parse("NpdId:x\r\nAppId:Ảnh1\r\nDeploymentMode:FUTURE_MODE\r\n");Assert.AreEqual("Ảnh1",r.Records.Single().AppId);}
  [TestMethod][DataRow("")][DataRow("Operation Failed") ]public void FailureStructured(string s){var r=new AdobeLicenseInformationParser().Parse(s);Assert.IsFalse(r.Successful);Assert.IsTrue(r.Warnings.Count>0);}
 }
 [TestClass]public class ClassificationTests{
  static readonly DateTimeOffset Now=DateTimeOffset.Parse("2027-01-01T00:00:00Z");
  [TestMethod]public void SharedFutureLicensedPastExpired(){Assert.AreEqual(LicenseStatus.Licensed,AdobeLicenseClassifier.Status(Record("SHARED_DEVICE",Now.AddDays(1)),Now));Assert.AreEqual(LicenseStatus.Expired,AdobeLicenseClassifier.Status(Record("SHARED_DEVICE",Now.AddDays(-1)),Now));}
  [TestMethod]public void NamedUserNeedsOnline(){Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,AdobeLicenseClassifier.Status(Record("NAMED_USER_EDUCATION_LAB",Now.AddDays(1)),Now));}
  [TestMethod]public void UnknownModeUnknown(){Assert.AreEqual(LicenseStatus.Unknown,AdobeLicenseClassifier.Status(Record("FUTURE",Now.AddDays(1)),Now));}
  [TestMethod]public void FrlExpiryPolicy(){Assert.AreEqual(LicenseStatus.Licensed,AdobeLicenseClassifier.Status(Record("FRL_CONNECTED",Now.AddDays(1)),Now));Assert.AreEqual("FeatureRestrictedIsolated",AdobeLicenseClassifier.Model("FRL_ISOLATED"));}
  static AdobeLicenseRecord Record(string mode,DateTimeOffset expiry)=>new AdobeLicenseRecord{DeploymentMode=mode,LicenseExpiry=expiry,DatesUnambiguous=true};
 }
 [TestClass]public class DetectionTests{
  [TestMethod]public void CatalogIsDeterministic(){Assert.AreEqual("Photoshop1",AdobeProductCatalog.ResolveAppId("Adobe Photoshop 2026"));Assert.AreEqual("Adobe Photoshop",AdobeProductCatalog.ResolveName("Photoshop1"));Assert.AreEqual("Adobe application Future1",AdobeProductCatalog.ResolveName("Future1"));}
  [TestMethod][DataRow("Adobe Inc.","Adobe Photoshop 2026",true)][DataRow("Adobe Inc.","Adobe Creative Cloud",false)][DataRow("Adobe Inc.","Adobe Genuine Service",false)][DataRow("Adobe Inc.","Camera Raw",false)][DataRow("Other","Adobe Photoshop",false)]public void FiltersInfrastructure(string publisher,string name,bool expected)=>Assert.AreEqual(expected,AdobeInstallationDetector.IsProduct(publisher,name));
  [TestMethod]public void ExactAppIdMatchesOnly(){var p=new[]{new AdobeInstalledProduct{AppId="Photoshop1"},new AdobeInstalledProduct{AppId="Illustrator1"}};Assert.AreSame(p[0],AdobeProductMatcher.Match(new AdobeLicenseRecord{AppId="Photoshop1"},p));Assert.IsNull(AdobeProductMatcher.Match(new AdobeLicenseRecord{AppId="Photo"},p));}
 }
 [TestClass]public class ProviderTests{
  [TestMethod]public async Task FixedReadOnlyCommandHidden(){var r=new FakeRunner{Result=new ProcessExecutionResult{ExitCode=0,StandardOutput="NpdId:x\nAppId:Photoshop1"}};var x=await new AdobeLicensingEvidenceProvider(r,new FakeLocator(true),new AdobeLicenseInformationParser()).ReadLicenseInformationAsync(CancellationToken.None);Assert.IsTrue(x.Successful);Assert.AreEqual("--licenseInformation",r.Request.Arguments);Assert.IsTrue(r.Request.CreateNoWindow);Assert.AreEqual(TimeSpan.FromSeconds(30),r.Request.Timeout);}
  [TestMethod]public async Task MissingDoesNotRun(){var r=new FakeRunner();var x=await new AdobeLicensingEvidenceProvider(r,new FakeLocator(false),new AdobeLicenseInformationParser()).ReadLicenseInformationAsync(CancellationToken.None);Assert.IsNull(r.Request);Assert.IsFalse(x.Successful);}
  [TestMethod][DataRow(true,false,0,"timed out")][DataRow(false,true,0,"could not start")][DataRow(false,false,2,"non-zero")]public async Task FailuresStructured(bool timeout,bool start,int exit,string expected){var r=new FakeRunner{Result=new ProcessExecutionResult{TimedOut=timeout,StartFailure=start,ExitCode=exit}};var x=await new AdobeLicensingEvidenceProvider(r,new FakeLocator(true),new AdobeLicenseInformationParser()).ReadLicenseInformationAsync(CancellationToken.None);StringAssert.Contains(x.Warnings.Single(),expected);}
  [TestMethod]public async Task StderrIsSuppressed(){var r=new FakeRunner{Result=new ProcessExecutionResult{StandardOutput="NpdId:x\nAppId:Photoshop1",StandardError="private diagnostic"}};var x=await new AdobeLicensingEvidenceProvider(r,new FakeLocator(true),new AdobeLicenseInformationParser()).ReadLicenseInformationAsync(CancellationToken.None);Assert.IsFalse(string.Join("|",x.Warnings).Contains("private diagnostic"));}
 }
 [TestClass]public class ScannerTests{
  [TestMethod]public async Task NamedUserInstallIsNeverLicensed(){var r=await Scan(new[]{Product("Adobe Photoshop 2026","Photoshop1")},Array.Empty<AdobeLicenseRecord>(),false,false);Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single().Status);Assert.IsNull(r.Single().IsLicensed);}
  [TestMethod]public async Task SharedFutureLicensedWithOfficialRecord(){var license=new AdobeLicenseRecord{AppId="Photoshop1",DeploymentMode="SHARED_DEVICE",LicenseExpiry=Now.AddDays(2),DatesUnambiguous=true};var r=await Scan(new[]{Product("Adobe Photoshop","Photoshop1")},new[]{license},true,true);Assert.AreEqual(LicenseStatus.Licensed,r.Single().Status);}
  [TestMethod]public async Task StaleCacheRequiresOnline(){var license=new AdobeLicenseRecord{AppId="Photoshop1",DeploymentMode="SHARED_DEVICE",LicenseExpiry=Now.AddDays(2),CacheExpiry=Now.AddDays(-1),DatesUnambiguous=true};var r=await Scan(new[]{Product("Adobe Photoshop","Photoshop1")},new[]{license},true,true);Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single().Status);}
  [TestMethod]public async Task ServiceRunningDoesNotLicense(){var r=await Scan(new[]{Product("Adobe Illustrator","Illustrator1")},Array.Empty<AdobeLicenseRecord>(),false,true);Assert.AreNotEqual(LicenseStatus.Licensed,r.Single().Status);}
  [TestMethod]public async Task NoProductsReturnsEmpty(){Assert.AreEqual(0,(await Scan(Array.Empty<AdobeInstalledProduct>(),Array.Empty<AdobeLicenseRecord>(),false,false)).Count);}
  [TestMethod]public async Task OrphanLicenseDoesNotCreateInstalledProduct(){Assert.AreEqual(0,(await Scan(Array.Empty<AdobeInstalledProduct>(),new[]{new AdobeLicenseRecord{AppId="Photoshop1"}},false,false)).Count);}
  [TestMethod]public async Task CancellationPropagates(){var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsExceptionAsync<OperationCanceledException>(()=>new AdobeLicenseScanner(new FakeDetector(Array.Empty<AdobeInstalledProduct>()),new FakeEvidence(Array.Empty<AdobeLicenseRecord>()),new FakeConfig(false),new FakeService(false,false),new Clock()).ScanAsync(new SystemContext{OsName="Windows"},c.Token));}
  static readonly DateTimeOffset Now=DateTimeOffset.Parse("2027-01-01T00:00:00Z");static AdobeInstalledProduct Product(string n,string id)=>new AdobeInstalledProduct{ProductName=n,AppId=id,DetectionSource="fixture"};static Task<IReadOnlyList<LicenseResult>> Scan(IReadOnlyList<AdobeInstalledProduct>p,IReadOnlyList<AdobeLicenseRecord>r,bool config,bool service)=>new AdobeLicenseScanner(new FakeDetector(p),new FakeEvidence(r),new FakeConfig(config),new FakeService(true,service),new Clock()).ScanAsync(new SystemContext{OsName="Windows"},CancellationToken.None);
 }
 class FakeRunner:IProcessRunner{public ProcessExecutionRequest Request;public ProcessExecutionResult Result=new ProcessExecutionResult();public Task<ProcessExecutionResult>RunAsync(ProcessExecutionRequest r,CancellationToken c){Request=r;return Task.FromResult(Result);}}
 class FakeLocator:IAdobeLicensingToolkitLocator{readonly bool x;public FakeLocator(bool v){x=v;}public AdobeToolkitInfo Locate()=>new AdobeToolkitInfo{Exists=x,Path=@"C:\app\tools\adobe\adobe-licensing-toolkit.exe"};}
 class FakeDetector:IAdobeInstallationDetector{readonly IReadOnlyList<AdobeInstalledProduct>x;public FakeDetector(IReadOnlyList<AdobeInstalledProduct>v){x=v;}public IReadOnlyList<AdobeInstalledProduct>Detect(SystemContext c,out IReadOnlyList<string>w){w=Array.Empty<string>();return x;}}
 class FakeEvidence:IAdobeLicensingEvidenceProvider{readonly IReadOnlyList<AdobeLicenseRecord>x;public FakeEvidence(IReadOnlyList<AdobeLicenseRecord>v){x=v;}public Task<AdobeLicenseInformationResult>ReadLicenseInformationAsync(CancellationToken c)=>Task.FromResult(new AdobeLicenseInformationResult{Successful=true,Records=x});}
 class FakeConfig:IAdobeSharedDeviceConfigurationDetector{readonly bool x;public FakeConfig(bool v){x=v;}public AdobeSharedDeviceConfiguration Detect()=>new AdobeSharedDeviceConfiguration{Present=x,Count=x?2:0};}
 class FakeService:IAdobeServiceStatusProvider{readonly bool f,r;public FakeService(bool a,bool b){f=a;r=b;}public AdobeServiceStatus GetStatus()=>new AdobeServiceStatus{Found=f,Running=r};}
 class Clock:ISystemClock{public DateTimeOffset UtcNow=>DateTimeOffset.Parse("2027-01-01T00:00:00Z");}
 [TestClass]public class RegistrationTests{[TestMethod]public void ProductionOrderIsStable(){var ids=WinLic.Application.ProductionScannerFactory.CreateAll(new FakeRunner(),new Clock()).Select(x=>x.ScannerId).ToArray();CollectionAssert.AreEqual(new[]{"microsoft.windows","microsoft.office","autodesk.desktop","adobe.desktop"},ids);}}
}
