using System;using System.Collections.Generic;using System.Linq;using System.Threading;using System.Threading.Tasks;using LicenseScope.Core.Contracts;using LicenseScope.Core.Models;using LicenseScope.SketchUp.Classification;using LicenseScope.SketchUp.Contracts;using LicenseScope.SketchUp.Models;
namespace LicenseScope.SketchUp
{
 public sealed class SketchUpLicenseScanner:ILicenseScanner
 {
  readonly ISketchUpInstallationDetector detector;readonly ISketchUpSubscriptionEvidenceProvider subscription;readonly ISketchUpClassicEvidenceProvider classic;public SketchUpLicenseScanner(ISketchUpInstallationDetector d,ISketchUpSubscriptionEvidenceProvider s,ISketchUpClassicEvidenceProvider c){detector=d;subscription=s;classic=c;}public string ScannerId=>"trimble.sketchup";public string VendorName=>"Trimble";public bool IsApplicable(SystemContext context)=>context!=null&&(context.OsName.IndexOf("Windows",StringComparison.OrdinalIgnoreCase)>=0||!string.IsNullOrWhiteSpace(context.WindowsDirectory));
  public Task<IReadOnlyList<LicenseResult>>ScanAsync(SystemContext context,CancellationToken token){token.ThrowIfCancellationRequested();var products=detector.Detect(context,out var detectionWarnings);var results=new List<LicenseResult>();foreach(var product in products){token.ThrowIfCancellationRequested();var sub=subscription.Detect(product,token);token.ThrowIfCancellationRequested();var old=classic.Detect(product,token);var type=SketchUpLicenseClassifier.Type(product,sub,old);var warnings=new List<string>(detectionWarnings);if(!string.IsNullOrWhiteSpace(sub.Warning))warnings.Add(sub.Warning);if(!string.IsNullOrWhiteSpace(old.Warning))warnings.Add(old.Warning);if(type=="Subscription")warnings.Add("Subscription and device authorization require periodic online verification; session metadata is not entitlement proof.");if(type=="ClassicNetwork")warnings.Add("Classic network configuration does not prove seat availability or checkout; server details are suppressed.");if(type=="Unknown")warnings.Add("No authoritative read-only local license status source was found.");var evidence=new List<ScanEvidence>{new ScanEvidence{Source=product.DetectionSource,Name="Installation",Value="Observed",Confidence=ConfidenceLevel.Medium},new ScanEvidence{Source="SketchUp profile metadata",Name="Version profile present",Value=sub.VersionProfilePresent?"Yes":"No",Confidence=ConfidenceLevel.Low},new ScanEvidence{Source="SketchUp session metadata",Name="Session artifact present",Value=sub.SessionArtifactPresent?"Yes":"No",Confidence=ConfidenceLevel.Low},new ScanEvidence{Source="SketchUp Classic metadata",Name="Classic artifact present",Value=old.ClassicArtifactPresent?"Yes":"No",Confidence=ConfidenceLevel.Low},new ScanEvidence{Source="SketchUp Classic metadata",Name="Network configuration present",Value=old.NetworkConfigurationPresent?"Yes":"No",Confidence=ConfidenceLevel.Low}};if(product.LayOutInstalled)evidence.Add(new ScanEvidence{Source=product.DetectionSource,Name="LayOut component",Value="Installed",Confidence=ConfidenceLevel.Low});if(product.StyleBuilderInstalled)evidence.Add(new ScanEvidence{Source=product.DetectionSource,Name="Style Builder component",Value="Installed",Confidence=ConfidenceLevel.Low});results.Add(new LicenseResult{ScannerId=ScannerId,Vendor=VendorName,ProductName=product.ProductName,ProductVersion=product.Version,Installed=true,Status=SketchUpLicenseClassifier.Status(type),IsLicensed=null,LicenseType=type,Confidence=ConfidenceLevel.Low,Evidence=evidence,Warnings=warnings.Distinct().ToArray()});}return Task.FromResult((IReadOnlyList<LicenseResult>)results.OrderBy(x=>x.ProductName,StringComparer.OrdinalIgnoreCase).ThenBy(x=>x.ProductVersion,StringComparer.OrdinalIgnoreCase).ToArray());}
 }
}
