using System.Collections.Generic;

namespace WinLicApp
{
    public enum Lang { EN, VIE }

    /// <summary>Complete EN / VIE string table for WinLic Manager.</summary>
    public static class L
    {
        public static Lang Current { get; set; } = Lang.VIE;

        private static readonly Dictionary<string, (string EN, string VIE)> S = new()
        {
            // ── Window / header ─────────────────────────────────────────────────
            ["AppTitle"]         = ("Windows Licensing & Information Manager",
                                    "Trình Quản Lý Bản Quyền Windows"),
            ["AdminOk"]          = ("✔  Running as Administrator — all features available",
                                    "✔  Đang chạy với quyền Quản trị viên — đầy đủ tính năng"),
            ["AdminWarn"]        = ("⚠  Not running as Administrator — options 4, 5, 6 will fail",
                                    "⚠  Không chạy với quyền Quản trị — tùy chọn 4, 5, 6 sẽ thất bại"),
            ["BtnElevate"]       = ("⚡ Relaunch as Admin",    "⚡ Khởi Lại Với Quyền Admin"),
            ["BtnAbout"]         = ("About",                   "Giới Thiệu"),

            // ── About dialog ─────────────────────────────────────────────────────
            ["About_Title"]       = ("About — WinLic Manager",
                                    "Giới thiệu — WinLic Manager"),
            ["About_Version"]     = ("Version 1.0 (beta)",          "Phiên bản 1.0 (beta)"),
            ["About_Author"]      = ("Author",                      "Tác giả"),
            ["About_GitHub"]      = ("GitHub",                      "GitHub"),
            ["About_Repo"]        = ("Repository",                  "Kho mã nguồn"),
            ["About_Close"]       = ("Close",                       "Đóng"),
            ["About_Desc"]        = ("A graphical Windows licensing management utility for inspecting product keys, activation status, BIOS OEM keys, and managing Windows Software Licensing (slmgr).",
                                    "Công cụ quản lý bản quyền Windows với giao diện đồ họa — hỗ trợ xem Key Bản Quyền, trạng thái kích hoạt, Key OEM BIOS, và quản lý dịch vụ cấp phép Windows (slmgr)."),

            // ── Sidebar labels ───────────────────────────────────────────────────
            ["LblReadOnly"]      = ("READ-ONLY",        "CHỈ ĐỌC"),
            ["LblAdmin"]         = ("REQUIRES ADMIN",   "CẦN QUYỀN ADMIN"),
            ["Btn1"]             = ("1  Version & BIOS Key",   "1  Phiên bản & Key BIOS"),
            ["Btn2"]             = ("2  License Info (dli)",   "2  Thông tin Bản quyền"),
            ["Btn3"]             = ("3  Inspect Keys",         "3  Xem Key Bản Quyền"),
            ["Btn4"]             = ("4  Test & Apply Key",     "4  Kiểm thử Key mới"),
            ["Btn5"]             = ("5  Uninstall Key",        "5  Gỡ cài đặt Key Bản Quyền"),
            ["Btn6"]             = ("6 — Reset Activation (Rearm)",  "6 — Đặt Lại Kích Hoạt (Rearm)"),
            ["Btn7"]             = ("7 — 3rd Party Activation Audit", "7 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),
            ["BtnClear"]         = ("Clear Log",               "Xóa nhật ký"),

            // ── Log action headers ───────────────────────────────────────────────
            ["Act1"]             = ("Option 1 — Windows Version & BIOS OEM Key",
                                    "Tùy chọn 1 — Phiên bản Windows & Key Bản Quyền OEM BIOS"),
            ["Act2"]             = ("Option 2 — License Channel & Type  (slmgr /dli)",
                                    "Tùy chọn 2 — Kênh & Loại Bản Quyền  (slmgr /dli)"),
            ["Act3"]             = ("Option 3 — Inspect Active & Backup Keys",
                                    "Tùy chọn 3 — Xem Key Bản Quyền đang dùng & dự phòng"),
            ["Act4"]             = ("Option 4 — Test & Apply Product Key",
                                    "Tùy chọn 4 — Kiểm thử Key Bản Quyền mới"),
            ["Act5"]             = ("Option 5 — Uninstall Current Product Key",
                                    "Tùy chọn 5 — Gỡ cài đặt Key Bản Quyền hiện tại"),
            ["Act6"]             = ("Option 6 — Reset Licensing Status / Rearm",
                                    "Tùy chọn 6 — Đặt lại Trạng thái Bản quyền / Rearm"),

            // ── Elevation / admin ─────────────────────────────────────────────────
            ["ElevateQ"]         = ("This tool works best with Administrator privileges.\n\nRelaunch as Administrator now?\n\nChoose No to continue in read-only mode.",
                                    "Công cụ này cần quyền Quản trị viên để hoạt động đầy đủ.\n\nKhởi lại với quyền Quản trị viên ngay bây giờ?\n\nChọn Không để tiếp tục ở chế độ chỉ đọc."),
            ["ElevateTitle"]     = ("Elevation Required", "Yêu Cầu Quyền Admin"),
            ["AdminReqMsg"]      = ("Please use the '⚡ Relaunch as Admin' button in the header.",
                                    "Vui lòng dùng nút '⚡ Khởi Lại Với Quyền Admin' ở đầu trang."),
            ["AdminReqTitle"]    = ("Admin Required", "Cần Quyền Admin"),
            ["ElevateFail"]      = ("Elevation failed: ", "Không thể nâng cấp quyền: "),

            // ── Dialog titles (shared) ────────────────────────────────────────────
            ["Confirm_Title"]    = ("Confirm",      "Xác nhận"),
            ["ShowKey_Title"]    = ("Key Display",  "Hiển thị Key Bản Quyền"),
            ["ShowKey_Q"]        = ("Show the full product key?\n(No = show last 5 chars only)",
                                    "Hiển thị đầy đủ Key Bản Quyền?\n(Không = chỉ hiện 5 ký tự cuối)"),

            // ── Status bar / general ──────────────────────────────────────────────
            ["Ready"]            = ("Ready",        "Sẵn sàng"),
            ["LogCleared"]       = ("Log cleared.", "Đã xóa nhật ký."),
            ["Startup_Ready"]    = ("WinLic Manager v1.0 (beta) — ready.",
                                    "WinLic Manager v1.0 (beta) — sẵn sàng."),
            ["Startup_NoAdmin"]  = ("Running without admin. Options 4, 5, 6 are blocked.",
                                    "Đang chạy không có quyền Admin. Tùy chọn 4, 5, 6 bị chặn."),

            // ── InputDialog buttons ───────────────────────────────────────────────
            ["Dialog_OK"]        = ("OK",       "Xác nhận"),
            ["Dialog_Cancel"]    = ("Cancel",   "Hủy"),

            // ── Fetch messages ────────────────────────────────────────────────────
            ["Fetch_OS"]         = ("Querying OS information…",
                                    "Đang truy vấn thông tin hệ điều hành…"),
            ["Fetch_BiosKey"]    = ("Checking BIOS/UEFI firmware OEM key…",
                                    "Đang kiểm tra Key Bản Quyền OEM trên BIOS/UEFI…"),
            ["Fetch_License"]    = ("Querying active Windows license (WMI)…",
                                    "Đang truy vấn bản quyền Windows đang hoạt động (WMI)…"),
            ["Fetch_BiosKey2"]   = ("Checking BIOS/UEFI OEM key…",
                                    "Đang kiểm tra Key Bản Quyền OEM trên BIOS/UEFI…"),
            ["Fetch_RegKey"]     = ("Reading registry backup key…",
                                    "Đang đọc Key Bản Quyền dự phòng từ Registry…"),

            // ── Data labels (LogData) ─────────────────────────────────────────────
            ["D_OsEdition"]      = ("OS Edition:",           "Phiên bản Windows:"),
            ["D_Version"]        = ("Version:",              "Số phiên bản:"),
            ["D_Build"]          = ("Build:",                "Số build:"),
            ["D_Arch"]           = ("Architecture:",         "Kiến trúc hệ thống:"),
            ["D_Edition"]        = ("Edition:",              "Ấn bản:"),
            ["D_Channel"]        = ("Channel:",              "Kênh phân phối:"),
            ["D_PartialKey"]     = ("Partial Key:",          "Key một phần:"),
            ["D_BiosOemKey"]     = ("BIOS OEM Key:",         "Key Bản Quyền OEM BIOS:"),
            ["D_RegBackupKey"]   = ("Registry Backup Key:",  "Key Bản Quyền dự phòng:"),
            ["D_Activation"]     = ("Activation:",           "Kích hoạt:"),

            // ── License status texts ──────────────────────────────────────────────
            ["LS_0"]             = ("Unlicensed",                     "Chưa được cấp phép"),
            ["LS_1"]             = ("Licensed (Permanently Activated)","Đã được cấp phép (Kích hoạt vĩnh viễn)"),
            ["LS_2"]             = ("OOB Grace Period",               "Thời gian ân hạn OOB"),
            ["LS_3"]             = ("OOT Grace Period",               "Thời gian ân hạn OOT"),
            ["LS_4"]             = ("Non-Genuine Grace Period",       "Thời gian ân hạn không chính hãng"),
            ["LS_5"]             = ("Notification Mode",              "Chế độ thông báo"),
            ["LS_6"]             = ("Extended Grace Period",          "Thời gian ân hạn mở rộng"),
            ["LS_Unknown"]       = ("Unknown",                        "Không xác định"),

            // ── BIOS OEM key edition detection ─────────────────────────────────────
            ["Fetch_OemEdition"]    = ("Identifying edition from BIOS OEM key…",
                                      "Đang xác định ấn bản từ Key Bản Quyền OEM BIOS…"),
            ["OemEd_Found"]         = ("Edition match found:",         "Phát hiện ấn bản tương ứng:"),
            ["OemEd_NoMatch"]       = ("Edition could not be determined from key alone.",
                                      "Không thể xác định ấn bản chỉ từ Key Bản Quyền."),
            ["OemEd_Hint"]          = ("Tip: install the key (Option 4) to let Windows confirm the edition.",
                                      "Gợi ý: cài đặt Key (Tùy chọn 4) để Windows xác nhận ấn bản."),

            // ── Digital Entitlement detection ────────────────────────────────────
            ["DE_Confirmed"]        = ("Activation method:  Digital Entitlement (hardware-bound license)",
                                      "Phương thức kích hoạt:  Digital Entitlement (bản quyền gắn phần cứng)"),
            ["DE_Explain1"]         = ("Windows is licensed via a Digital Entitlement stored on Microsoft's servers.",
                                      "Windows được cấp phép qua Digital Entitlement lưu trên máy chủ Microsoft."),
            ["DE_Explain2"]         = ("This license is bound to your hardware (motherboard fingerprint) and/or your Microsoft Account.",
                                      "Bản quyền này gắn với phần cứng (dấu vân tay bo mạch chủ) và/hoặc tài khoản Microsoft của bạn."),
            ["DE_Explain3"]         = ("The active product key shown above is a generic placeholder — the real activation lives in Microsoft's cloud.",
                                      "Key Bản Quyền đang dùng ở trên là key chung thay thế — kích hoạt thực sự nằm trên cloud của Microsoft."),
            ["DE_KeyMismatch"]      = ("The BIOS OEM key and Registry Backup key may differ from the active key — this is normal for DE-activated systems.",
                                      "Key Bản Quyền OEM BIOS và dự phòng có thể khác Key đang dùng — điều này bình thường với hệ thống kích hoạt bằng DE."),
            ["DE_Verify"]           = ("To confirm: Settings → System → Activation → look for 'Digital License'",
                                      "Để xác nhận: Cài đặt → Hệ thống → Kích hoạt → tìm 'Giấy phép kỹ thuật số'"),
            ["DE_NotActivated"]     = ("Activation method:  Digital Entitlement placeholder key detected — but status is NOT Licensed.",
                                      "Phương thức kích hoạt:  Phát hiện key chung DE — nhưng trạng thái KHÔNG được kích hoạt."),
            ["KMS_Detected"]        = ("Activation method:  KMS (Volume/Corporate License)",
                                      "Phương thức kích hoạt:  KMS (Bản quyền doanh nghiệp/tập thể)"),
            ["KMS_Server"]          = ("KMS Server:",                  "Máy chủ KMS:"),
            ["MAK_Detected"]        = ("Activation method:  MAK / Retail / OEM key (standard activation)",
                                      "Phương thức kích hoạt:  MAK / Retail / OEM (kích hoạt tiêu chuẩn)"),

            // ── Option 7 — 3rd-party activation audit ────────────────────────────
            ["Act7"]              = ("Option 7 — 3rd Party Activation Audit",
                                    "Tùy chọn 7 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),

            // preamble
            ["P7_Header"]        = ("══ WHAT THIS SCAN CHECKS ══",
                                    "══ CÁC KIỂM TRA TRONG LẦN QUÉT NÀY ══"),
            ["P7_CanDetect1"]    = ("① KMS server name / registry → detects local KMS emulators (KMSpico, KMSAuto, KMS_VL_ALL, vlmcsd…)",
                                    "① Tên máy chủ KMS / registry → phát hiện KMS giả lập cục bộ (KMSpico, KMSAuto, KMS_VL_ALL, vlmcsd…)"),
            ["P7_CanDetect2"]    = ("② Localhost port 1688 probe → confirms a live local KMS listener is running",
                                    "② Kiểm tra cổng 1688 trên localhost → xác nhận dịch vụ KMS cục bộ đang hoạt động"),
            ["P7_CanDetect3"]    = ("③ System services → residual activation services that survive reboots",
                                    "③ Dịch vụ hệ thống → dịch vụ kích hoạt cài cố định, tồn tại qua các lần khởi động lại"),
            ["P7_CanDetect4"]    = ("④ Scheduled tasks → periodic re-activation tasks common in KMSpico/KMSAuto",
                                    "④ Tác vụ định kỳ → tác vụ tự động kích hoạt lại, phổ biến ở KMSpico/KMSAuto"),
            ["P7_CanDetect5"]    = ("⑤ Known file/folder paths → installation leftovers from common tools",
                                    "⑤ Đường dẫn tập tin/thư mục → phần còn lại sau khi cài đặt công cụ kích hoạt"),
            ["P7_CanDetect6"]    = ("⑥ Running processes → active activation tool processes at scan time",
                                    "⑥ Tiến trình đang chạy → công cụ kích hoạt đang hoạt động tại thời điểm quét"),
            ["P7_LimitHeader"]   = ("══ KNOWN LIMITATIONS — CANNOT DETECT ══",
                                    "══ GIỚI HẠN ĐÃ BIẾT — KHÔNG THỂ PHÁT HIỆN ══"),
            ["P7_Limit1"]        = ("• HWID-based tools (MAS HWID, HWIDGEN): exploit Microsoft's own activation API to generate a genuine Digital Entitlement. The resulting license is 100% authentic and indistinguishable from a purchased one — even Microsoft cannot tell the difference.",
                                    "• Công cụ kiểu HWID (MAS HWID, HWIDGEN): khai thác API kích hoạt của Microsoft để tạo Digital Entitlement thật. Bản quyền thu được là 100% xác thực và không thể phân biệt với bản quyền mua — ngay cả Microsoft cũng không phân biệt được."),
            ["P7_Limit2"]        = ("• Cleaned activations: if the activation tool was fully removed after use, all filesystem and registry traces are gone. The activation itself persists but the tool is undetectable.",
                                    "• Kích hoạt đã dọn sạch: nếu công cụ bị gỡ hoàn toàn sau khi dùng, mọi dấu vết trên tập tin và registry đều mất. Kích hoạt vẫn còn đó nhưng công cụ không để lại vết."),
            ["P7_Limit3"]        = ("• Legacy SLIC/OEM BIOS patching (Windows Loader era): modifies firmware tables at a level not visible to software-only analysis.",
                                    "• Vá SLIC/OEM BIOS kiểu cũ (thời Windows Loader): sửa đổi bảng firmware ở mức không thể thấy qua phân tích phần mềm đơn thuần."),
            ["P7_Limit4"]        = ("• KMS38: activates until year 2038 using a token trick. Hard to distinguish from legitimate corporate activation unless the KMS machine is still set to localhost.",
                                    "• KMS38: kích hoạt đến năm 2038 bằng thủ thuật token. Khó phân biệt với bản quyền doanh nghiệp hợp lệ trừ khi máy chủ KMS vẫn trỏ localhost."),

            // per-check context strings
            ["P7_KmsExplain"]    = ("KMS (Key Management Service) is legitimate Microsoft technology for corporate volume licensing. Piracy tools abuse it by running a local emulator on 127.x.x.x that tricks Windows into believing it contacted a real corporate KMS server.",
                                    "KMS (Key Management Service) là công nghệ hợp lệ của Microsoft dùng cho bản quyền doanh nghiệp. Công cụ lậu lạm dụng bằng cách chạy máy chủ giả lập cục bộ trên 127.x.x.x để đánh lừa Windows rằng đã kết nối máy chủ KMS doanh nghiệp thật."),
            ["P7_Port1688Explain"] = ("Port 1688 is the standard KMS activation port. If this port is open on localhost, a KMS server emulator is actively listening — the single strongest individual indicator of local KMS-based piracy.",
                                    "Cổng 1688 là cổng kích hoạt KMS tiêu chuẩn. Nếu cổng này mở trên localhost, một KMS giả lập đang lắng nghe — đây là dấu hiệu đơn lẻ mạnh nhất của kích hoạt KMS lậu cục bộ."),
            ["P7_ServiceExplain"] = ("KMS emulators often install as Windows services to survive reboots and periodically re-trigger activation. Well-known service names are matched below.",
                                    "KMS giả lập thường cài đặt dưới dạng dịch vụ Windows để tồn tại qua khởi động lại và định kỳ kích hoạt lại. Các tên dịch vụ đã biết được kiểm tra bên dưới."),
            ["P7_TaskExplain"]   = ("Activation tools like KMSpico create scheduled tasks (e.g. 'AutoKMS') that re-activate Windows periodically to prevent grace-period expiry.",
                                    "Công cụ như KMSpico tạo tác vụ định kỳ (ví dụ 'AutoKMS') để kích hoạt lại Windows theo chu kỳ, ngăn hết hạn thời gian ân hạn."),
            ["P7_FileExplain"]   = ("Installation folders, executables (KMSELDI.exe), and patched system files are checked against a list of known tool locations.",
                                    "Thư mục cài đặt, tập tin thực thi (KMSELDI.exe) và tập tin hệ thống bị vá được kiểm tra đối chiếu danh sách đường dẫn đã biết của các công cụ."),
            ["P7_ProcExplain"]   = ("Some activation tools leave resident processes. This check lists any currently running processes whose names match known activation tools.",
                                    "Một số công cụ kích hoạt để lại tiến trình thường trú. Kiểm tra này liệt kê các tiến trình đang chạy có tên trùng với công cụ kích hoạt đã biết."),

            // results
            ["P7_Intro"]         = ("Scanning for local KMS emulators, suspicious services, tasks, files, and processes…",
                                    "Đang quét KMS giả lập, dịch vụ, tác vụ, tập tin và tiến trình đáng ngờ…"),
            ["Fetch_KmsHost"]    = ("① Checking KMS server name (registry + WMI)…",
                                    "① Kiểm tra tên máy chủ KMS (registry + WMI)…"),
            ["Fetch_Port1688"]   = ("② Probing localhost:1688 (KMS port)…",
                                    "② Kiểm tra cổng localhost:1688 (cổng KMS)…"),
            ["Fetch_Services"]   = ("③ Scanning system services…",
                                    "③ Quét dịch vụ hệ thống…"),
            ["Fetch_Tasks"]      = ("④ Scanning scheduled tasks…",
                                    "④ Quét tác vụ định kỳ…"),
            ["Fetch_Files"]      = ("⑤ Scanning known tool paths…",
                                    "⑤ Quét đường dẫn công cụ đã biết…"),
            ["Fetch_Procs"]      = ("⑥ Scanning running processes…",
                                    "⑥ Quét tiến trình đang chạy…"),
            ["P7_KmsLocal"]      = ("KMS GIẢ LẬP CỤC BỘ — Máy chủ KMS trỏ đến localhost/127.x.x.x!",
                                    "KMS GIẢ LẬP CỤC BỘ — Máy chủ KMS trỏ đến localhost/127.x.x.x!"),
            ["P7_KmsName"]       = ("KMS server configured:",    "Máy chủ KMS đã cấu hình:"),
            ["P7_KmsNone"]       = ("No KMS server configured.", "Không có máy chủ KMS nào được cấu hình."),
            ["P7_KmsExternal"]   = ("KMS server is external — consistent with a legitimate corporate deployment.",
                                    "Máy chủ KMS là địa chỉ bên ngoài — phù hợp triển khai doanh nghiệp hợp lệ."),
            ["P7_Port1688Open"]  = ("Port 1688 OPEN on localhost — a local KMS listener is actively running!",
                                    "Cổng 1688 ĐANG MỞ trên localhost — có dịch vụ KMS cục bộ đang chạy!"),
            ["P7_Port1688Closed"] = ("Port 1688 on localhost is closed (no local KMS listener).",
                                    "Cổng 1688 trên localhost đã đóng — không có dịch vụ KMS cục bộ."),
            ["P7_ServiceFound"]   = ("Suspicious service detected:",        "Phát hiện dịch vụ đáng ngờ:"),
            ["P7_NoServices"]     = ("No suspicious services found.",       "Không phát hiện dịch vụ đáng ngờ."),
            ["P7_TaskFound"]      = ("Suspicious scheduled task detected:", "Phát hiện tác vụ định kỳ đáng ngờ:"),
            ["P7_NoTasks"]        = ("No suspicious scheduled tasks found.","Không phát hiện tác vụ đáng ngờ."),
            ["P7_FileFound"]      = ("Known activation tool path found:",   "Phát hiện đường dẫn công cụ kích hoạt:"),
            ["P7_NoFiles"]        = ("No known activation tool files found.","Không phát hiện tập tin công cụ."),
            ["P7_ProcFound"]      = ("Suspicious process running:",         "Phát hiện tiến trình đáng ngờ:"),
            ["P7_NoProcs"]        = ("No suspicious processes running.",    "Không phát hiện tiến trình đáng ngờ."),
            ["P7_Clean"]          = ("No 3rd-party activation indicators detected — system appears clean.",
                                    "Không phát hiện dấu hiệu kích hoạt bên thứ ba — hệ thống có vẻ sạch."),
            ["P7_Suspicious"]     = ("One or more suspicious indicators found — review the results above.",
                                    "Phát hiện một hoặc nhiều dấu hiệu đáng ngờ — xem kết quả ở trên."),
            ["P7_Critical"]       = ("CRITICAL: Local KMS emulator confirmed. Windows is almost certainly pirate-activated.",
                                    "NGHIÊM TRỌNG: Xác nhận KMS cục bộ. Windows gần như chắc chắn dùng kích hoạt lậu."),

            // ── Option 1 ──────────────────────────────────────────────────────────
            ["O1_BiosDetectedCtx"] = ("BIOS/UEFI OEM key detected in firmware.",
                                      "Phát hiện Key Bản Quyền OEM trên firmware BIOS/UEFI."),
            ["O1_BiosKey"]         = ("BIOS OEM Key:  ",  "Key Bản Quyền OEM BIOS:  "),
            ["O1_BiosNone"]        = ("BIOS OEM Key:  None detected in BIOS/UEFI firmware.",
                                      "Key Bản Quyền OEM BIOS:  Không phát hiện trên firmware BIOS/UEFI."),

            // ── Option 2 ──────────────────────────────────────────────────────────
            ["O2_Note"]            = ("slmgr natively reveals only the last 5 characters of the active key.",
                                      "slmgr chỉ hiển thị 5 ký tự cuối của Key Bản Quyền đang hoạt động."),
            ["O2_NoOutput"]        = ("No output received from slmgr /dli.",
                                      "Không nhận được kết quả từ slmgr /dli."),
            ["O2_LicenseStatus"]   = ("License Status:  ", "Trạng thái bản quyền:  "),

            // ── Option 3 ──────────────────────────────────────────────────────────
            ["O3_DigitalLic"]      = ("Digital License detected — key is a generic setup key:",
                                      "Phát hiện Digital License — Key đang dùng là Key Bản Quyền chung:"),
            ["O3_DigitalLicInfo"]  = ("Windows is activated via a Digital License tied to your hardware / Microsoft Account.",
                                      "Windows được kích hoạt qua Digital License gắn với phần cứng / tài khoản Microsoft của bạn."),
            ["O3_NoLicense"]       = ("No active Windows product license found via WMI.",
                                      "Không tìm thấy bản quyền Windows đang hoạt động qua WMI."),
            ["O3_BiosNone"]        = ("None detected",  "Không phát hiện"),
            ["O3_BiosDetected"]    = ("✔ Detected",     "✔ Đã phát hiện"),
            ["O3_RegNone"]         = ("None found",     "Không tìm thấy"),
            ["O3_KeysFoundCtx"]    = ("Keys were found.", "Đã tìm thấy Key Bản Quyền."),
            ["O3_KeyBios"]         = ("BIOS OEM Key:         ",         "Key Bản Quyền OEM BIOS:      "),
            ["O3_KeyReg"]          = ("Registry Backup Key:  ",         "Key Bản Quyền dự phòng:      "),
            ["O3_Mismatch"]        = ("Registry Backup Key does NOT match the currently active license key.",
                                      "Key Bản Quyền dự phòng KHÔNG khớp với Key Bản Quyền đang hoạt động."),
            ["O3_MismatchReason"]  = ("This can happen after an edition upgrade or a change in activation method.",
                                      "Điều này có thể xảy ra sau khi nâng cấp ấn bản hoặc thay đổi phương thức kích hoạt."),
            ["O3_ActivePartial"]   = ("  Active partial:        ",      "  Key một phần đang dùng:  "),
            ["O3_BackupEnds"]      = ("  Backup key ends with:  ",      "  Key dự phòng kết thúc với:  "),
            ["O3_ConfirmRemove"]   = ("Registry Backup Key does not match the active key.\n\nRemove the stale Registry Backup Key?\n(Your active activation will NOT be affected.)",
                                      "Key Bản Quyền dự phòng không khớp với Key đang hoạt động.\n\nXóa Key Bản Quyền dự phòng lỗi thời?\n(Trạng thái kích hoạt hiện tại sẽ KHÔNG bị ảnh hưởng.)"),
            ["O3_RegKeyRemoved"]   = ("Registry backup key removed.",
                                      "Đã xóa Key Bản Quyền dự phòng từ Registry."),
            ["O3_RemoveErr"]       = ("Could not remove key: ",         "Không thể xóa Key Bản Quyền: "),
            ["O3_RegReadErr"]      = ("Registry read: ",                "Lỗi đọc Registry: "),
            ["O3_KeyMatch"]        = ("Registry Backup Key matches the active product key.",
                                      "Key Bản Quyền dự phòng khớp với Key Bản Quyền đang hoạt động."),
            ["O3_DlvQ"]            = ("Also run the full slmgr /dlv report?",
                                      "Có muốn chạy báo cáo đầy đủ slmgr /dlv không?"),
            ["O3_DlvTitle"]        = ("slmgr /dlv", "slmgr /dlv"),
            ["O3_Activation"]      = ("Activation:  ", "Kích hoạt:  "),

            // ── Option 4 ──────────────────────────────────────────────────────────
            ["O4_Info1"]           = ("Key testing works by attempting local installation.",
                                      "Kiểm thử Key Bản Quyền bằng cách thử cài đặt trên máy."),
            ["O4_Info2"]           = ("Your existing activation will NOT be harmed by testing a mismatched key.",
                                      "Trạng thái kích hoạt hiện tại sẽ KHÔNG bị ảnh hưởng khi kiểm thử Key không tương thích."),
            ["O4_Prompt"]          = ("Enter the 25-character product key:\n\nFormat:  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
                                      "Nhập Key Bản Quyền gồm 25 ký tự:\n\nĐịnh dạng:  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"),
            ["O4_PromptTitle"]     = ("Enter Product Key",  "Nhập Key Bản Quyền"),
            ["O4_Cancelled"]       = ("Cancelled — no key entered.",
                                      "Đã hủy — không nhập Key Bản Quyền."),
            ["O4_BadFormat"]       = ("Invalid format. Key must be  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
                                      "Định dạng không hợp lệ. Key phải có dạng  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"),
            ["O4_ShowKeyCtx"]      = ("About to install the product key.",
                                      "Sắp cài đặt Key Bản Quyền."),
            ["O4_Installing"]      = ("Installing Key Bản Quyền:  ",  "Đang cài đặt Key Bản Quyền:  "),
            ["O4_Success1"]        = ("Key accepted! Windows will attempt online activation automatically.",
                                      "Key Bản Quyền được chấp nhận! Windows sẽ tự động kích hoạt trực tuyến."),
            ["O4_Success2"]        = ("Check activation status with Option 2.",
                                      "Kiểm tra trạng thái kích hoạt ở Tùy chọn 2."),
            ["O4_Fail"]            = ("Key was rejected.",  "Key Bản Quyền bị từ chối."),
            ["O4_DiagSku"]         = ("SKU Mismatch — key belongs to a different Windows edition (e.g. Home vs Pro).",
                                      "SKU không khớp — Key thuộc ấn bản Windows khác (ví dụ: Home và Pro)."),
            ["O4_DiagInvalid"]     = ("Invalid Key — the key is invalid or mistyped.",
                                      "Key không hợp lệ — Key Bản Quyền bị sai hoặc nhập nhầm."),
            ["O4_DiagBlocked"]     = ("Blocked Key — this key has been blacklisted by Microsoft.",
                                      "Key bị chặn — Key Bản Quyền này đã bị Microsoft thu hồi."),
            ["O4_DiagGeneral"]     = ("Check the error code for more information.",
                                      "Kiểm tra mã lỗi để biết thêm thông tin."),

            // ── Option 5 ──────────────────────────────────────────────────────────
            ["O5_Confirm"]         = ("⚠  WARNING\n\nThis will uninstall the current Windows product key AND clear it from the registry.\n\nYour Windows will become UNACTIVATED.\n\nContinue?",
                                      "⚠  CẢNH BÁO\n\nThao tác này sẽ gỡ cài đặt Key Bản Quyền Windows hiện tại VÀ xóa khỏi Registry.\n\nWindows của bạn sẽ trở thành CHƯA ĐƯỢC KÍCH HOẠT.\n\nTiếp tục?"),
            ["O5_Cancelled"]       = ("Cancelled.", "Đã hủy."),
            ["O5_Uninstalling"]    = ("Uninstalling product key  (slmgr /upk)…",
                                      "Đang gỡ cài đặt Key Bản Quyền  (slmgr /upk)…"),
            ["O5_Clearing"]        = ("Clearing key from registry  (slmgr /cpky)…",
                                      "Đang xóa Key Bản Quyền khỏi Registry  (slmgr /cpky)…"),
            ["O5_Done"]            = ("Product key uninstalled and registry cleared.",
                                      "Đã gỡ cài đặt Key Bản Quyền và xóa khỏi Registry."),

            // ── Option 6 ──────────────────────────────────────────────────────────
            ["O6_Confirm"]         = ("⚠  WARNING\n\nThis resets the licensing status and activation timers (rearm).\n\nA computer restart is required for changes to take effect.\n\nContinue?",
                                      "⚠  CẢNH BÁO\n\nThao tác này đặt lại trạng thái bản quyền và bộ đếm kích hoạt (rearm).\n\nCần khởi động lại máy tính để áp dụng thay đổi.\n\nTiếp tục?"),
            ["O6_Cancelled"]       = ("Cancelled.", "Đã hủy."),
            ["O6_Rearming"]        = ("Executing  slmgr /rearm…",  "Đang thực thi  slmgr /rearm…"),
            ["O6_Done"]            = ("Rearm complete. Restart your computer for changes to take effect.",
                                      "Rearm hoàn tất. Khởi động lại máy tính để áp dụng thay đổi."),
            ["O6_RestartQ"]        = ("Restart the computer now?", "Khởi động lại máy tính ngay bây giờ?"),
            ["O6_Restarting"]      = ("Restarting in 5 seconds…",  "Đang khởi động lại sau 5 giây…"),
        };

        public static string Get(string key) =>
            S.TryGetValue(key, out var v) ? (Current == Lang.EN ? v.EN : v.VIE) : key;
    }
}
