using System.Collections.Generic;

namespace WinLicApp
{
    public enum Lang { EN, VIE }

    /// <summary>Complete EN / VIE string table for WinLic Manager.</summary>
    public static class L
    {
        public static Lang Current { get; set; } = Lang.VIE;

        private static readonly Dictionary<string, (string EN, string VIE)> S = new()
        {
            // ── Window / header ─────────────────────────────────────────────────
            ["AppTitle"]         = ("Windows Licensing & Information Manager",
                                    "Trình Quản Lý Bản Quyền Windows"),
            ["AdminOk"]          = ("✔  Running as Administrator — all features available",
                                    "✔  Đang chạy với quyền Quản trị viên — đầy đủ tính năng"),
            ["AdminWarn"]        = ("⚠  Not running as Administrator — options 4, 5, 6 require elevation",
                                    "⚠  Chưa có quyền Quản trị viên — tùy chọn 4, 5, 6 cần nâng quyền"),
            ["BtnElevate"]       = ("⚡ Relaunch as Admin",    "⚡ Khởi Lại Với Quyền Admin"),
            ["BtnAbout"]         = ("About",                   "Giới Thiệu"),

            // ── About dialog ─────────────────────────────────────────────────────
            ["About_Title"]       = ("About — WinLic Manager",
                                    "Giới thiệu — WinLic Manager"),
            ["About_Version"]     = ("Version 1.0 (beta1)",         "Phiên bản 1.0 (beta1)"),
            ["About_Author"]      = ("Author",                      "Tác giả"),
            ["About_GitHub"]      = ("GitHub",                      "GitHub"),
            ["About_Repo"]        = ("Repository",                  "Kho mã nguồn"),
            ["About_Close"]       = ("Close",                       "Đóng"),
            ["About_Desc"]        = ("A graphical Windows licensing management utility for inspecting product keys, activation status, BIOS OEM keys, and managing Windows Software Licensing (slmgr).",
                                    "Công cụ quản lý bản quyền Windows với giao diện đồ họa — hỗ trợ xem Key Bản Quyền, trạng thái kích hoạt, Key OEM BIOS, và quản lý dịch vụ cấp phép Windows (slmgr)."),

            // ── Sidebar button labels ─────────────────────────────────────────────
            ["LblReadOnly"]      = ("READ-ONLY",        "CHỈ ĐỌC"),
            ["LblAdmin"]         = ("REQUIRES ADMIN",   "CẦN QUYỀN ADMIN"),
            ["Btn1"]             = ("1 — OS Version & OEM BIOS Key",     "1 — Phiên bản OS & Key OEM BIOS"),
            ["Btn2"]             = ("2 — License Channel & Type",         "2 — Kênh & Loại Bản Quyền"),
            ["Btn3"]             = ("3 — Inspect Keys & Activation",      "3 — Key & Trạng thái Kích Hoạt"),
            ["Btn4"]             = ("4 — Test & Install Product Key",     "4 — Kiểm thử & Cài Key Bản Quyền"),
            ["Btn5"]             = ("5 — Uninstall License Key",          "5 — Gỡ Key Bản Quyền"),
            ["Btn6"]             = ("6 — Reset Activation (Rearm)",       "6 — Đặt Lại Kích Hoạt (Rearm)"),
            ["Btn7"]             = ("7 — 3rd Party Activation Audit",     "7 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),
            ["BtnAuditSettings"] = ("⚙  Audit Scan Settings",            "⚙  Cài đặt Kiểm tra"),
            ["BtnClear"]         = ("Clear Log",                          "Xóa nhật ký"),

            // ── Log action headers ───────────────────────────────────────────────
            ["Act1"]             = ("Option 1 — OS Version & BIOS OEM Key",
                                    "Tùy chọn 1 — Phiên bản OS & Key Bản Quyền OEM BIOS"),
            ["Act2"]             = ("Option 2 — License Channel & Type  (slmgr /dli)",
                                    "Tùy chọn 2 — Kênh & Loại Bản Quyền  (slmgr /dli)"),
            ["Act3"]             = ("Option 3 — Inspect Active Keys & Activation Status",
                                    "Tùy chọn 3 — Xem Key Đang Dùng & Trạng thái Kích Hoạt"),
            ["Act4"]             = ("Option 4 — Test & Install Product Key",
                                    "Tùy chọn 4 — Kiểm thử & Cài Key Bản Quyền"),
            ["Act5"]             = ("Option 5 — Uninstall Current License Key",
                                    "Tùy chọn 5 — Gỡ Key Bản Quyền hiện tại"),
            ["Act6"]             = ("Option 6 — Reset Licensing Status / Rearm",
                                    "Tùy chọn 6 — Đặt lại Trạng thái Bản quyền / Rearm"),
            ["Act7"]             = ("Option 7 — 3rd Party Activation Audit",
                                    "Tùy chọn 7 — Kiểm Tra Kích Hoạt Bên Thứ Ba"),

            // ── Elevation / admin ─────────────────────────────────────────────────
            ["ElevateQ"]         = ("This tool works best with Administrator privileges.\n\nRelaunch as Administrator now?\n\nChoose No to continue in read-only mode.",
                                    "Công cụ này cần quyền Quản trị viên để hoạt động đầy đủ.\n\nKhởi lại với quyền Quản trị viên ngay bây giờ?\n\nChọn Không để tiếp tục ở chế độ chỉ đọc."),
            ["ElevateTitle"]     = ("Elevation Required", "Yêu Cầu Quyền Admin"),
            ["AdminReqMsg"]      = ("Please use the '⚡ Relaunch as Admin' button in the header.",
                                    "Vui lòng dùng nút '⚡ Khởi Lại Với Quyền Admin' ở đầu trang."),
            ["AdminReqTitle"]    = ("Admin Required", "Cần Quyền Admin"),
            ["ElevateFail"]      = ("Elevation failed: ", "Không thể nâng cấp quyền: "),
            ["ElevateFromOption"] = ("This option requires Administrator privileges.\n\nRelaunch WinLic Manager as Administrator now?\n\nNote: The app will restart and the current log will be cleared.",
                                    "Tùy chọn này yêu cầu quyền Quản trị viên.\n\nKhởi lại WinLic Manager với quyền Admin ngay bây giờ?\n\nLưu ý: Ứng dụng sẽ khởi động lại và nhật ký hiện tại sẽ bị xóa."),

            // ── Dialog titles (shared) ────────────────────────────────────────────
            ["Confirm_Title"]    = ("Confirm",      "Xác nhận"),
            ["ShowKey_Title"]    = ("Key Display",  "Hiển thị Key Bản Quyền"),
            ["ShowKey_Q"]        = ("Show the full product key?\n(No = show last 5 chars only)",
                                    "Hiển thị đầy đủ Key Bản Quyền?\n(Không = chỉ hiện 5 ký tự cuối)"),

            // ── Status bar / general ──────────────────────────────────────────────
            ["Ready"]            = ("Ready",        "Sẵn sàng"),
            ["LogCleared"]       = ("Log cleared.", "Đã xóa nhật ký."),
            ["Startup_Ready"]    = ("WinLic Manager v1.0 (beta1) — ready.",
                                    "WinLic Manager v1.0 (beta1) — sẵn sàng."),
            ["Startup_NoAdmin"]  = ("Running without Administrator. Options 1, 2, 3, 7 are fully available. Options 4, 5, 6 will prompt for elevation when selected.",
                                    "Không có quyền Quản trị. Tùy chọn 1, 2, 3, 7 hoạt động bình thường. Tùy chọn 4, 5, 6 sẽ yêu cầu nâng quyền khi được chọn."),

            // ── InputDialog buttons ───────────────────────────────────────────────
            ["Dialog_OK"]        = ("OK",       "Xác nhận"),
            ["Dialog_Cancel"]    = ("Cancel",   "Hủy"),

            // ── Fetch messages ────────────────────────────────────────────────────
            ["Fetch_OS"]         = ("Querying OS information…",
                                    "Đang truy vấn thông tin hệ điều hành…"),
            ["Fetch_BiosKey"]    = ("Checking BIOS/UEFI firmware OEM key…",
                                    "Đang kiểm tra Key Bản Quyền OEM trên BIOS/UEFI…"),
            ["Fetch_License"]    = ("Querying active Windows license (WMI)…",
                                    "Đang truy vấn bản quyền Windows đang hoạt động (WMI)…"),
            ["Fetch_BiosKey2"]   = ("Checking BIOS/UEFI OEM key…",
                                    "Đang kiểm tra Key Bản Quyền OEM trên BIOS/UEFI…"),
            ["Fetch_RegKey"]     = ("Reading registry backup key…",
                                    "Đang đọc Key Bản Quyền dự phòng từ Registry…"),

            // ── Data labels (LogData) ─────────────────────────────────────────────
            ["D_OsEdition"]      = ("OS Edition:",           "Phiên bản Windows:"),
            ["D_Version"]        = ("Version:",              "Số phiên bản:"),
            ["D_Build"]          = ("Build:",                "Số build:"),
            ["D_Arch"]           = ("Architecture:",         "Kiến trúc hệ thống:"),
            ["D_Edition"]        = ("Edition:",              "Ấn bản:"),
            ["D_Channel"]        = ("Channel:",              "Kênh phân phối:"),
            ["D_PartialKey"]     = ("Partial Key:",          "Key một phần:"),
            ["D_BiosOemKey"]     = ("BIOS OEM Key:",         "Key Bản Quyền OEM BIOS:"),
            ["D_RegBackupKey"]   = ("Registry Backup Key:",  "Key Dự phòng (Registry):"),
            ["D_Activation"]     = ("Activation:",           "Kích hoạt:"),

            // ── License status texts ──────────────────────────────────────────────
            ["LS_0"]             = ("Unlicensed",                     "Chưa được cấp phép"),
            ["LS_1"]             = ("Licensed (Permanently Activated)","Đã được cấp phép (Kích hoạt vĩnh viễn)"),
            ["LS_2"]             = ("OOB Grace Period",               "Thời gian ân hạn OOB"),
            ["LS_3"]             = ("OOT Grace Period",               "Thời gian ân hạn OOT"),
            ["LS_4"]             = ("Non-Genuine Grace Period",       "Thời gian ân hạn không chính hãng"),
            ["LS_5"]             = ("Notification Mode",              "Chế độ thông báo"),
            ["LS_6"]             = ("Extended Grace Period",          "Thời gian ân hạn mở rộng"),
            ["LS_Unknown"]       = ("Unknown",                        "Không xác định"),

            // ── BIOS OEM key edition detection ─────────────────────────────────────
            ["Fetch_OemEdition"]    = ("Identifying edition from BIOS OEM key…",
                                      "Đang xác định ấn bản từ Key Bản Quyền OEM BIOS…"),
            ["OemEd_Found"]         = ("Edition match found:",         "Phát hiện ấn bản tương ứng:"),
            ["OemEd_NoMatch"]       = ("Edition could not be determined from key alone.",
                                      "Không thể xác định ấn bản chỉ từ Key Bản Quyền."),
            ["OemEd_Hint"]          = ("Tip: install the key (Option 4) to let Windows confirm the edition.",
                                      "Gợi ý: cài đặt Key (Tùy chọn 4) để Windows xác nhận ấn bản."),

            // ── Digital Entitlement detection ────────────────────────────────────
            ["DE_Confirmed"]        = ("Activation method:  Digital Entitlement (hardware-bound license)",
                                      "Phương thức kích hoạt:  Digital Entitlement (bản quyền gắn phần cứng)"),
            ["DE_Explain1"]         = ("Windows is licensed via a Digital Entitlement stored on Microsoft's servers.",
                                      "Windows được cấp phép qua Digital Entitlement lưu trên máy chủ Microsoft."),
            ["DE_Explain2"]         = ("This license is bound to your hardware (motherboard fingerprint) and/or your Microsoft Account.",
                                      "Bản quyền này gắn với phần cứng (dấu vân tay bo mạch chủ) và/hoặc tài khoản Microsoft của bạn."),
            ["DE_Explain3"]         = ("The active product key shown above is a generic placeholder — the real activation lives in Microsoft's cloud.",
                                      "Key Bản Quyền đang dùng ở trên là key chung thay thế — kích hoạt thực sự nằm trên cloud của Microsoft."),
            ["DE_KeyMismatch"]      = ("The BIOS OEM key and Registry Backup key may differ from the active key — this is normal for DE-activated systems.",
                                      "Key Bản Quyền OEM BIOS và dự phòng có thể khác Key đang dùng — điều này bình thường với hệ thống kích hoạt bằng DE."),
            ["DE_Verify"]           = ("To confirm: Settings → System → Activation → look for 'Digital License'",
                                      "Để xác nhận: Cài đặt → Hệ thống → Kích hoạt → tìm 'Giấy phép kỹ thuật số'"),
            ["DE_NotActivated"]     = ("Activation method:  Digital Entitlement placeholder key detected — but status is NOT Licensed.",
                                      "Phương thức kích hoạt:  Phát hiện key chung DE — nhưng trạng thái KHÔNG được kích hoạt."),
            ["KMS_Detected"]        = ("Activation method:  KMS (Volume/Corporate License)",
                                      "Phương thức kích hoạt:  KMS (Bản quyền doanh nghiệp/tập thể)"),
            ["KMS_Server"]          = ("KMS Server:",                  "Máy chủ KMS:"),
            ["MAK_Detected"]        = ("Activation method:  MAK / Retail / OEM key (standard activation)",
                                      "Phương thức kích hoạt:  MAK / Retail / OEM (kích hoạt tiêu chuẩn)"),

            // ── Option 2 ──────────────────────────────────────────────────────────
            ["O2_Note"]            = ("Note: slmgr /dli shows a summary of the active license. Only the last 5 characters of the product key are revealed.",
                                      "Lưu ý: slmgr /dli hiển thị tóm tắt bản quyền đang hoạt động. Chỉ 5 ký tự cuối của Key Bản Quyền được hiển thị."),
            ["O2_NoOutput"]        = ("No output received from slmgr /dli.",
                                      "Không nhận được kết quả từ slmgr /dli."),
            ["O2_LicenseStatus"]   = ("License Status:  ", "Trạng thái bản quyền:  "),

            // ── Option 3 ──────────────────────────────────────────────────────────
            ["O3_DigitalLic"]      = ("Digital License detected — key is a generic setup key:",
                                      "Phát hiện Digital License — Key đang dùng là Key Bản Quyền chung:"),
            ["O3_DigitalLicInfo"]  = ("Windows is activated via a Digital License tied to your hardware / Microsoft Account.",
                                      "Windows được kích hoạt qua Digital License gắn với phần cứng / tài khoản Microsoft của bạn."),
            ["O3_NoLicense"]       = ("No active Windows product license found via WMI.",
                                      "Không tìm thấy bản quyền Windows đang hoạt động qua WMI."),
            ["O3_BiosNone"]        = ("None detected",  "Không phát hiện"),
            ["O3_BiosDetected"]    = ("✔ Detected",     "✔ Đã phát hiện"),
            ["O3_RegNone"]         = ("None found",     "Không tìm thấy"),
            ["O3_KeysFoundCtx"]    = ("Keys were found in BIOS and/or Registry.",
                                      "Phát hiện Key Bản Quyền trong BIOS và/hoặc Registry."),
            ["O3_KeyBios"]         = ("BIOS OEM Key:          ",  "Key OEM BIOS:          "),
            ["O3_KeyReg"]          = ("Registry Backup Key:   ",  "Key Dự phòng (Registry):  "),
            ["O3_Mismatch"]        = ("⚠  Registry Backup Key does NOT match the currently active license key.",
                                      "⚠  Key Dự phòng trong Registry KHÔNG khớp với Key Bản Quyền đang hoạt động."),
            ["O3_MismatchReason"]  = ("This can happen after an edition upgrade or a change in activation method.",
                                      "Điều này có thể xảy ra sau khi nâng cấp ấn bản hoặc thay đổi phương thức kích hoạt."),
            ["O3_ActivePartial"]   = ("     Active key ends with:          ",  "     Key đang dùng kết thúc với:  "),
            ["O3_BackupEnds"]      = ("     Registry Backup Key ends with:  ",  "     Key Dự phòng Registry kết thúc với:  "),
            ["O3_ConfirmRemove"]   = ("The Registry Backup Key (stored at HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SoftwareProtectionPlatform → BackupProductKeyDefault) does not match the active key.\n\nThis stale backup key is likely a leftover from a previous activation or edition upgrade.\n\nRemove the stale Registry Backup Key?\n\nNote: Your active Windows activation will NOT be affected — this only removes the backup copy.",
                                      "Key Dự phòng trong Registry (lưu tại HKLM\\...\\SoftwareProtectionPlatform → BackupProductKeyDefault) không khớp với Key đang hoạt động.\n\nKey dự phòng này có thể là tàn dư từ lần kích hoạt hoặc nâng cấp ấn bản trước đó.\n\nXóa Key Dự phòng trong Registry?\n\nLưu ý: Trạng thái kích hoạt Windows hiện tại sẽ KHÔNG bị ảnh hưởng — chỉ xóa bản sao lưu."),
            ["O3_RegKeyRemoved"]   = ("Registry Backup Key removed.",
                                      "Đã xóa Key Dự phòng khỏi Registry."),
            ["O3_RemoveErr"]       = ("Could not remove key: ",         "Không thể xóa Key Bản Quyền: "),
            ["O3_RegReadErr"]      = ("Registry read error: ",          "Lỗi đọc Registry: "),
            ["O3_KeyMatch"]        = ("✔  Registry Backup Key matches the active product key.",
                                      "✔  Key Dự phòng trong Registry khớp với Key Bản Quyền đang hoạt động."),
            ["O3_DlvQ"]            = ("Also run the full slmgr /dlv extended report?\n\nThis reveals:\n  • License channel & sub-channel (Retail / OEM / Volume)\n  • Full SKU ID and description\n  • KMS server configuration & client count\n  • Remaining rearm (reset) count\n  • Activation expiry / grace-period deadline\n  • Unique machine ID (CMID)\n\nUseful for diagnosing activation issues in detail.",
                                      "Có muốn chạy báo cáo mở rộng slmgr /dlv không?\n\nBáo cáo này hiển thị:\n  • Kênh & kênh phụ bản quyền (Retail / OEM / Volume)\n  • SKU ID đầy đủ và mô tả\n  • Cấu hình máy chủ KMS & số lượng client\n  • Số lần rearm (đặt lại) còn lại\n  • Thời hạn kích hoạt / thời gian ân hạn\n  • ID máy duy nhất (CMID)\n\nHữu ích để chẩn đoán chi tiết vấn đề kích hoạt."),
            ["O3_DlvTitle"]        = ("slmgr /dlv — Extended License Report",
                                      "slmgr /dlv — Báo cáo Bản quyền Mở rộng"),
            ["O3_Activation"]      = ("Activation:  ", "Kích hoạt:  "),

            // ── Option 1 ──────────────────────────────────────────────────────────
            ["O1_BiosDetectedCtx"] = ("A BIOS/UEFI OEM key was found embedded in your firmware.",
                                      "Phát hiện Key Bản Quyền OEM được nhúng trong firmware BIOS/UEFI."),
            ["O1_BiosKey"]         = ("BIOS OEM Key:  ",  "Key Bản Quyền OEM BIOS:  "),
            ["O1_BiosNone"]        = ("No OEM key detected in BIOS/UEFI firmware.",
                                      "Không phát hiện Key Bản Quyền OEM trên firmware BIOS/UEFI."),

            // ── Option 4 ──────────────────────────────────────────────────────────
            ["O4_Info1"]           = ("Key testing works by attempting local installation of the entered key.",
                                      "Kiểm thử Key Bản Quyền bằng cách thử cài đặt key đã nhập trên máy."),
            ["O4_Info2"]           = ("Your existing activation will NOT be harmed if the key is rejected or belongs to a different edition.",
                                      "Trạng thái kích hoạt hiện tại sẽ KHÔNG bị ảnh hưởng nếu key bị từ chối hoặc thuộc ấn bản khác."),
            ["O4_Prompt"]          = ("Enter the 25-character product key:\n\nFormat:  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
                                      "Nhập Key Bản Quyền gồm 25 ký tự:\n\nĐịnh dạng:  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"),
            ["O4_PromptTitle"]     = ("Enter Product Key",  "Nhập Key Bản Quyền"),
            ["O4_Cancelled"]       = ("Cancelled — no key entered.",
                                      "Đã hủy — không nhập Key Bản Quyền."),
            ["O4_BadFormat"]       = ("Invalid format. Key must be  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
                                      "Định dạng không hợp lệ. Key phải có dạng  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"),
            ["O4_ShowKeyCtx"]      = ("About to install the product key.",
                                      "Sắp cài đặt Key Bản Quyền."),
            ["O4_Installing"]      = ("Installing key:  ",  "Đang cài đặt key:  "),
            ["O4_Success1"]        = ("Key accepted! Windows will attempt online activation automatically.",
                                      "Key Bản Quyền được chấp nhận! Windows sẽ tự động kích hoạt trực tuyến."),
            ["O4_Success2"]        = ("Check activation status with Option 3 or Option 2.",
                                      "Kiểm tra trạng thái kích hoạt ở Tùy chọn 3 hoặc Tùy chọn 2."),
            ["O4_Fail"]            = ("Key was rejected by Windows.",  "Key Bản Quyền bị Windows từ chối."),
            ["O4_DiagSku"]         = ("SKU Mismatch — key belongs to a different Windows edition (e.g. Home vs Pro).",
                                      "SKU không khớp — Key thuộc ấn bản Windows khác (ví dụ: Home và Pro)."),
            ["O4_DiagInvalid"]     = ("Invalid Key — the key is invalid or mistyped.",
                                      "Key không hợp lệ — Key Bản Quyền bị sai hoặc nhập nhầm."),
            ["O4_DiagBlocked"]     = ("Blocked Key — this key has been blacklisted by Microsoft.",
                                      "Key bị chặn — Key Bản Quyền này đã bị Microsoft thu hồi."),
            ["O4_DiagGeneral"]     = ("Check the error code for more information.",
                                      "Kiểm tra mã lỗi để biết thêm thông tin."),

            // ── Option 5 ──────────────────────────────────────────────────────────
            ["O5_Confirm"]         = ("⚠  WARNING\n\nThis will uninstall the current Windows product key AND clear it from the registry.\n\nWindows will become UNACTIVATED after this operation.\n\nContinue?",
                                      "⚠  CẢNH BÁO\n\nThao tác này sẽ gỡ cài đặt Key Bản Quyền Windows hiện tại VÀ xóa khỏi Registry.\n\nWindows sẽ trở thành CHƯA ĐƯỢC KÍCH HOẠT sau thao tác này.\n\nTiếp tục?"),
            ["O5_Cancelled"]       = ("Cancelled.", "Đã hủy."),
            ["O5_Uninstalling"]    = ("Uninstalling product key  (slmgr /upk)…",
                                      "Đang gỡ cài đặt Key Bản Quyền  (slmgr /upk)…"),
            ["O5_Clearing"]        = ("Clearing key from registry  (slmgr /cpky)…",
                                      "Đang xóa Key Bản Quyền khỏi Registry  (slmgr /cpky)…"),
            ["O5_Done"]            = ("Product key uninstalled and registry cleared.",
                                      "Đã gỡ cài đặt Key Bản Quyền và xóa khỏi Registry."),

            // ── Option 6 ──────────────────────────────────────────────────────────
            ["O6_Confirm"]         = ("⚠  WARNING\n\nThis resets the licensing status and activation timers (rearm).\n\nA computer restart is required for changes to take effect.\n\nContinue?",
                                      "⚠  CẢNH BÁO\n\nThao tác này đặt lại trạng thái bản quyền và bộ đếm kích hoạt (rearm).\n\nCần khởi động lại máy tính để áp dụng thay đổi.\n\nTiếp tục?"),
            ["O6_Cancelled"]       = ("Cancelled.", "Đã hủy."),
            ["O6_Rearming"]        = ("Executing  slmgr /rearm…",  "Đang thực thi  slmgr /rearm…"),
            ["O6_Done"]            = ("Rearm complete. Restart your computer for changes to take effect.",
                                      "Rearm hoàn tất. Khởi động lại máy tính để áp dụng thay đổi."),
            ["O6_RestartQ"]        = ("Restart the computer now?", "Khởi động lại máy tính ngay bây giờ?"),
            ["O6_Restarting"]      = ("Restarting in 5 seconds…",  "Đang khởi động lại sau 5 giây…"),

            // ── Option 7 — 3rd-party activation audit ────────────────────────────
            // preamble
            ["P7_Header"]        = ("══ WHAT THIS SCAN CHECKS ══",
                                    "══ CÁC KIỂM TRA TRONG LẦN QUÉT NÀY ══"),
            ["P7_CanDetect1"]    = ("① KMS server name / registry → detects local KMS emulators (KMSpico, KMSAuto, KMS_VL_ALL, vlmcsd…)",
                                    "① Tên máy chủ KMS / registry → phát hiện KMS giả lập cục bộ (KMSpico, KMSAuto, KMS_VL_ALL, vlmcsd…)"),
            ["P7_CanDetect2"]    = ("② Localhost port probe → confirms a live local KMS listener is running",
                                    "② Kiểm tra cổng localhost → xác nhận dịch vụ KMS cục bộ đang hoạt động"),
            ["P7_CanDetect3"]    = ("③ System services → residual activation services that survive reboots",
                                    "③ Dịch vụ hệ thống → dịch vụ kích hoạt cài cố định, tồn tại qua các lần khởi động lại"),
            ["P7_CanDetect4"]    = ("④ Scheduled tasks → periodic re-activation tasks common in KMSpico/KMSAuto",
                                    "④ Tác vụ định kỳ → tác vụ tự động kích hoạt lại, phổ biến ở KMSpico/KMSAuto"),
            ["P7_CanDetect5"]    = ("⑤ Known file/folder paths → installation leftovers from common tools",
                                    "⑤ Đường dẫn tập tin/thư mục → phần còn lại sau khi cài đặt công cụ kích hoạt"),
            ["P7_CanDetect6"]    = ("⑥ Running processes → active activation tool processes at scan time",
                                    "⑥ Tiến trình đang chạy → công cụ kích hoạt đang hoạt động tại thời điểm quét"),
            ["P7_LimitHeader"]   = ("══ KNOWN LIMITATIONS — CANNOT DETECT ══",
                                    "══ GIỚI HẠN ĐÃ BIẾT — KHÔNG THỂ PHÁT HIỆN ══"),
            ["P7_Limit1"]        = ("• HWID tools (MAS HWID, HWIDGEN): exploit Microsoft's own API to create a genuine Digital Entitlement — 100% authentic, indistinguishable from a purchased license.",
                                    "• Công cụ HWID (MAS HWID, HWIDGEN): khai thác API Microsoft để tạo Digital Entitlement thật — 100% xác thực, không thể phân biệt với bản quyền mua."),
            ["P7_Limit2"]        = ("• Cleaned activations: if the tool was fully removed after use, all filesystem and registry traces are gone — activation persists but is undetectable.",
                                    "• Kích hoạt đã dọn sạch: nếu công cụ bị gỡ hoàn toàn sau khi dùng, mọi dấu vết đều mất — kích hoạt vẫn còn nhưng không để lại vết."),
            ["P7_Limit3"]        = ("• Legacy SLIC/OEM BIOS patching (Windows Loader era): modifies firmware tables at a level not visible to software analysis.",
                                    "• Vá SLIC/OEM BIOS kiểu cũ (thời Windows Loader): sửa đổi bảng firmware ở mức không thể thấy qua phân tích phần mềm."),
            ["P7_Limit4"]        = ("• KMS38: activates until year 2038 via a token trick — hard to distinguish from legitimate corporate KMS unless server is still pointing to localhost.",
                                    "• KMS38: kích hoạt đến năm 2038 bằng thủ thuật token — khó phân biệt với doanh nghiệp hợp lệ trừ khi máy chủ KMS vẫn trỏ localhost."),

            // per-check context strings
            ["P7_KmsExplain"]    = ("KMS is legitimate Microsoft technology for corporate volume licensing. Piracy tools abuse it by running a local emulator on 127.x.x.x that tricks Windows into believing it contacted a real corporate KMS server.",
                                    "KMS là công nghệ hợp lệ của Microsoft dùng cho bản quyền doanh nghiệp. Công cụ lậu lạm dụng bằng cách chạy máy chủ giả lập cục bộ trên 127.x.x.x để đánh lừa Windows rằng đã kết nối máy chủ KMS thật."),
            ["P7_Port1688Explain"] = ("KMS activation port(s) listed below are probed on localhost. An open port means a local KMS emulator is actively listening — the strongest single indicator of local KMS-based piracy.",
                                    "Cổng kích hoạt KMS bên dưới được kiểm tra trên localhost. Cổng mở nghĩa là có KMS giả lập đang chạy cục bộ — đây là dấu hiệu đơn lẻ mạnh nhất của kích hoạt KMS lậu."),
            ["P7_ServiceExplain"] = ("KMS emulators often install as Windows services to survive reboots and periodically re-trigger activation. Well-known service names are matched below.",
                                    "KMS giả lập thường cài đặt dưới dạng dịch vụ Windows để tồn tại qua khởi động lại và định kỳ kích hoạt lại. Các tên dịch vụ đã biết được kiểm tra bên dưới."),
            ["P7_TaskExplain"]   = ("Activation tools like KMSpico create scheduled tasks (e.g. 'AutoKMS') that re-activate Windows periodically to prevent grace-period expiry.",
                                    "Công cụ như KMSpico tạo tác vụ định kỳ (ví dụ 'AutoKMS') để kích hoạt lại Windows theo chu kỳ, ngăn hết hạn thời gian ân hạn."),
            ["P7_FileExplain"]   = ("Known installation folders, executables (KMSELDI.exe), and patched system files are checked against a list of known tool locations.",
                                    "Thư mục cài đặt, tập tin thực thi (KMSELDI.exe) và tập tin hệ thống bị vá được kiểm tra đối chiếu danh sách đường dẫn đã biết."),
            ["P7_ProcExplain"]   = ("Some activation tools leave resident processes. This check lists any currently running processes whose names match known activation tools.",
                                    "Một số công cụ kích hoạt để lại tiến trình thường trú. Kiểm tra này liệt kê các tiến trình đang chạy có tên trùng với công cụ đã biết."),

            // scan step labels
            ["P7_Intro"]         = ("Starting scan…",
                                    "Bắt đầu quét…"),
            ["Fetch_KmsHost"]    = ("① Checking KMS server name (registry + WMI)…",
                                    "① Kiểm tra tên máy chủ KMS (registry + WMI)…"),
            ["Fetch_Port1688"]   = ("② Probing configured KMS port(s) on localhost…",
                                    "② Kiểm tra cổng KMS đã cấu hình trên localhost…"),
            ["Fetch_Services"]   = ("③ Scanning system services…",
                                    "③ Quét dịch vụ hệ thống…"),
            ["Fetch_Tasks"]      = ("④ Scanning scheduled tasks…",
                                    "④ Quét tác vụ định kỳ…"),
            ["Fetch_Files"]      = ("⑤ Scanning known tool paths…",
                                    "⑤ Quét đường dẫn công cụ đã biết…"),
            ["Fetch_Procs"]      = ("⑥ Scanning running processes…",
                                    "⑥ Quét tiến trình đang chạy…"),

            // scan results
            ["P7_KmsLocal"]      = ("LOCAL KMS EMULATOR — KMS server is pointing to localhost/127.x.x.x!",
                                    "KMS GIẢ LẬP CỤC BỘ — Máy chủ KMS trỏ đến localhost/127.x.x.x!"),
            ["P7_KmsName"]       = ("KMS server configured:",    "Máy chủ KMS đã cấu hình:"),
            ["P7_KmsNone"]       = ("No KMS server configured.", "Không có máy chủ KMS nào được cấu hình."),
            ["P7_KmsExternal"]   = ("KMS server is an external address — consistent with a legitimate corporate deployment.",
                                    "Máy chủ KMS là địa chỉ bên ngoài — phù hợp triển khai doanh nghiệp hợp lệ."),
            ["P7_PortOpen"]      = ("Port {0} OPEN on localhost — a local KMS listener is actively running!",
                                    "Cổng {0} ĐANG MỞ trên localhost — có dịch vụ KMS cục bộ đang chạy!"),
            ["P7_PortClosed"]    = ("Port {0} on localhost is closed (no local KMS listener).",
                                    "Cổng {0} trên localhost đã đóng — không có dịch vụ KMS cục bộ."),
            // legacy keys kept for reference
            ["P7_Port1688Open"]  = ("Port 1688 OPEN on localhost — a local KMS listener is actively running!",
                                    "Cổng 1688 ĐANG MỞ trên localhost — có dịch vụ KMS cục bộ đang chạy!"),
            ["P7_Port1688Closed"] = ("Port 1688 on localhost is closed (no local KMS listener).",
                                    "Cổng 1688 trên localhost đã đóng — không có dịch vụ KMS cục bộ."),
            ["P7_ServiceFound"]   = ("Suspicious service detected:",        "Phát hiện dịch vụ đáng ngờ:"),
            ["P7_NoServices"]     = ("No suspicious services found.",       "Không phát hiện dịch vụ đáng ngờ."),
            ["P7_TaskFound"]      = ("Suspicious scheduled task detected:", "Phát hiện tác vụ định kỳ đáng ngờ:"),
            ["P7_NoTasks"]        = ("No suspicious scheduled tasks found.","Không phát hiện tác vụ đáng ngờ."),
            ["P7_FileFound"]      = ("Known activation tool path found:",   "Phát hiện đường dẫn công cụ kích hoạt:"),
            ["P7_NoFiles"]        = ("No known activation tool files found.","Không phát hiện tập tin công cụ."),
            ["P7_ProcFound"]      = ("Suspicious process running:",         "Phát hiện tiến trình đáng ngờ:"),
            ["P7_NoProcs"]        = ("No suspicious processes running.",    "Không phát hiện tiến trình đáng ngờ."),
            ["P7_Clean"]          = ("No 3rd-party activation indicators detected — system appears clean.",
                                    "Không phát hiện dấu hiệu kích hoạt bên thứ ba — hệ thống có vẻ sạch."),
            ["P7_Suspicious"]     = ("One or more suspicious indicators found — review the results above.",
                                    "Phát hiện một hoặc nhiều dấu hiệu đáng ngờ — xem kết quả ở trên."),
            ["P7_Critical"]       = ("CRITICAL: Local KMS emulator confirmed. Windows is almost certainly pirate-activated.",
                                    "NGHIÊM TRỌNG: Xác nhận KMS cục bộ. Windows gần như chắc chắn dùng kích hoạt lậu."),
            ["P7_SummaryHeader"]  = ("Results",  "Kết quả"),

            // ── Settings dialog ───────────────────────────────────────────────────
            ["SD_Title"]    = ("Option 7 — Audit Scan Settings",
                               "Tùy chọn 7 — Cài đặt Kiểm tra"),
            ["SD_Desc"]     = ("Customize the scan lists used by the 3rd Party Activation Audit. Built-in defaults cannot be removed. Custom additions are saved to settings.ini next to the application.",
                               "Tùy chỉnh danh sách quét cho Kiểm tra Kích Hoạt Bên Thứ Ba. Mặc định tích hợp sẵn không thể xóa. Bổ sung của người dùng được lưu vào settings.ini cạnh ứng dụng."),
            ["SD_Ports"]    = ("KMS Ports to Probe",              "Cổng KMS cần kiểm tra"),
            ["SD_Services"] = ("Suspicious Service Names",        "Tên dịch vụ đáng ngờ"),
            ["SD_Tasks"]    = ("Suspicious Task Keywords",        "Từ khóa tác vụ đáng ngờ"),
            ["SD_Procs"]    = ("Suspicious Process Names",        "Tên tiến trình đáng ngờ"),
            ["SD_Files"]    = ("Custom File/Folder Paths",        "Đường dẫn tập tin/thư mục tùy chỉnh"),
            ["SD_Defaults"] = ("Built-in defaults (read-only):",  "Mặc định tích hợp sẵn (chỉ đọc):"),
            ["SD_Custom"]   = ("Custom additions (one per line):", "Bổ sung thêm (mỗi dòng một mục):"),
            ["SD_FilesNote"] = ("Built-in file/folder paths are computed from system environment variables at scan time. Add any extra paths here (one per line).",
                                "Đường dẫn tập tin/thư mục mặc định được tính từ biến môi trường hệ thống khi quét. Thêm đường dẫn bổ sung tại đây (mỗi dòng một mục)."),
            ["SD_SaveNote"] = ("Saved to settings.ini alongside the application.",
                               "Lưu vào settings.ini cạnh ứng dụng."),
            ["SD_Save"]     = ("Save",  "Lưu"),
            ["SD_Saved"]    = ("Settings saved to:", "Đã lưu cài đặt vào:"),
        };

        public static string Get(string key) =>
            S.TryGetValue(key, out var v) ? (Current == Lang.EN ? v.EN : v.VIE) : key;
    }
}
