using System; using System.Collections.Generic; using System.IO; using Microsoft.Win32; using WinLic.Core.Models; using WinLic.Scanners.Adobe.Contracts; using WinLic.Scanners.Adobe.Models;
namespace WinLic.Scanners.Adobe.Detection
{
 public sealed class AdobeInstallationDetector:IAdobeInstallationDetector
 {
  static readonly string[] Products={"Photoshop","Illustrator","Premiere Pro","After Effects","InDesign","Acrobat Pro","Acrobat Standard","Lightroom","Lightroom Classic","Audition","Animate","Dreamweaver","Media Encoder","Bridge","Character Animator","Fresco"};
  static readonly string[] Excluded={"Creative Cloud","Genuine","Desktop Service","IPC Broker","CCXProcess","CoreSync","Update Service","Content Manager","Identity Manager","Installer","Notification","Camera Raw","UXP","CEP","Fonts","Language Pack","Help","Library","Libraries","Uninstaller","Licensing"};
  public IReadOnlyList<AdobeInstalledProduct> Detect(SystemContext context,out IReadOnlyList<string>warnings){var map=new Dictionary<string,AdobeInstalledProduct>(StringComparer.OrdinalIgnoreCase);var notes=new List<string>();Read(RegistryView.Registry32,map,notes);if(Environment.Is64BitOperatingSystem)Read(RegistryView.Registry64,map,notes);var list=new List<AdobeInstalledProduct>(map.Values);list.Sort((a,b)=>string.Compare(a.ProductName+a.Version,b.ProductName+b.Version,StringComparison.OrdinalIgnoreCase));warnings=notes;return list;}
  public static bool IsProduct(string publisher,string name){if(publisher.IndexOf("Adobe",StringComparison.OrdinalIgnoreCase)<0)return false;foreach(var x in Excluded)if(name.IndexOf(x,StringComparison.OrdinalIgnoreCase)>=0)return false;foreach(var x in Products)if(name.IndexOf(x,StringComparison.OrdinalIgnoreCase)>=0)return true;return false;}
  static void Read(RegistryView view,IDictionary<string,AdobeInstalledProduct>map,ICollection<string>notes){try{using(var hive=RegistryKey.OpenBaseKey(RegistryHive.LocalMachine,view))using(var root=hive.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",false)){if(root==null)return;foreach(var keyName in root.GetSubKeyNames())using(var key=root.OpenSubKey(keyName,false)){var name=key?.GetValue("DisplayName") as string??"";var publisher=key?.GetValue("Publisher") as string??"";if(!IsProduct(publisher,name))continue;var version=key?.GetValue("DisplayVersion") as string??"";var location=key?.GetValue("InstallLocation") as string??"";map[name+"|"+version]=new AdobeInstalledProduct{ProductCode=keyName,AppId=AdobeProductCatalog.ResolveAppId(name),ProductName=name,Version=version,ReleaseYear=AdobeProductCatalog.ReleaseYear(name,version),Architecture=view==RegistryView.Registry64?"x64":"x86",InstallLocation=location,DetectionSource="Registry uninstall metadata ("+view+")"};}}}catch(Exception ex)when(ex is UnauthorizedAccessException||ex is System.Security.SecurityException||ex is IOException){notes.Add("Adobe installation metadata unavailable: "+ex.GetType().Name);}}
 }
 public static class AdobeProductCatalog
 {
  static readonly KeyValuePair<string,string>[] Map={new KeyValuePair<string,string>("Photoshop","Photoshop1"),new KeyValuePair<string,string>("Illustrator","Illustrator1"),new KeyValuePair<string,string>("Premiere Pro","PremierePro1"),new KeyValuePair<string,string>("After Effects","AfterEffects1"),new KeyValuePair<string,string>("InDesign","InDesign1"),new KeyValuePair<string,string>("Animate","Animate1"),new KeyValuePair<string,string>("Dreamweaver","Dreamweaver1"),new KeyValuePair<string,string>("Media Encoder","MediaEncoder1"),new KeyValuePair<string,string>("Lightroom Classic","LightroomClassic1")};
  public static string ResolveAppId(string name){foreach(var x in Map)if(name.IndexOf(x.Key,StringComparison.OrdinalIgnoreCase)>=0)return x.Value;return "";}
  public static string ResolveName(string appId){foreach(var x in Map)if(string.Equals(x.Value,appId,StringComparison.OrdinalIgnoreCase))return "Adobe "+x.Key;return string.IsNullOrWhiteSpace(appId)?"Adobe application":"Adobe application "+appId;}
  public static string ReleaseYear(string name,string version){for(var year=2035;year>=2000;year--)if(name.IndexOf(year.ToString(),StringComparison.Ordinal)>=0)return year.ToString();return version.Length>=4&&int.TryParse(version.Substring(0,4),out _)?version.Substring(0,4):"";}
 }
 public sealed class AdobeSharedDeviceConfigurationDetector:IAdobeSharedDeviceConfigurationDetector
 {
  public AdobeSharedDeviceConfiguration Detect(){var root=Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);var path=Path.Combine(root,"Adobe","OperatingConfigs");try{if(!Directory.Exists(path))return new AdobeSharedDeviceConfiguration();var count=Directory.GetFiles(path,"*",SearchOption.TopDirectoryOnly).Length;return new AdobeSharedDeviceConfiguration{Present=true,Count=count};}catch(Exception ex)when(ex is UnauthorizedAccessException||ex is IOException){return new AdobeSharedDeviceConfiguration{Present=true,Warning="Shared Device configuration count unavailable: "+ex.GetType().Name};}}
 }
}
