using System; using System.Collections.Generic; using System.Linq; using System.Threading; using System.Threading.Tasks; using Microsoft.VisualStudio.TestTools.UnitTesting; using LicenseScope.Core.Contracts; using LicenseScope.Core.Models; using LicenseScope.Autodesk; using LicenseScope.Autodesk.Acquisition; using LicenseScope.Autodesk.Classification; using LicenseScope.Autodesk.Contracts; using LicenseScope.Autodesk.Models; using LicenseScope.Autodesk.Parsing;
using LicenseScope.Core.Runtime;
namespace LicenseScope.Autodesk.Tests
{
 [TestClass] public class ParserTests {
  [TestMethod] public void ParsesMultipleAndDropsSensitiveFields(){var s="log\n[{\"feature_id\":\"ACD\",\"sel_prod_key\":\"001L1\",\"sel_prod_ver\":\"2025.0.0.F\",\"lic_method\":4,\"supported_lic_methods\":[1,4],\"lic_servers\":[\"@private-host\"],\"serial_number_sa\":\"123-12345678\"},{\"feature_id\":\"RVT\",\"lic_method\":1}]\nend";var r=new AdskLicensingListParser().Parse(s);Assert.IsTrue(r.Successful);Assert.AreEqual(2,r.Registrations.Count);Assert.IsTrue(r.Registrations.Single(x=>x.FeatureId=="ACD").HasConfiguredServers);var text=string.Join("|",r.Registrations.Select(x=>x.ToString()));Assert.IsFalse(text.Contains("private-host"));Assert.IsFalse(text.Contains("123-12345678"));}
  [DataTestMethod][DataRow("")][DataRow("not json")][DataRow("[{")] public void InvalidIsStructured(string s){var r=new AdskLicensingListParser().Parse(s);Assert.IsFalse(r.Successful);Assert.AreEqual(0,r.Registrations.Count);Assert.IsTrue(r.Warnings.Count>0);}
  [TestMethod] public void EmptyUnknownNullDuplicate(){var p=new AdskLicensingListParser();Assert.AreEqual(0,p.Parse("[]").Registrations.Count);var r=p.Parse("[{\"feature_id\":\"A\",\"lic_method\":null,\"new\":\"x\"},{\"feature_id\":\"A\",\"lic_method\":null}]");Assert.IsTrue(r.Successful);Assert.AreEqual(1,r.Registrations.Count);Assert.IsNull(r.Registrations[0].LicenseMethodCode);}
  [TestMethod] public void UnicodeAndLf(){var r=new AdskLicensingListParser().Parse("note\n[{\"feature_id\":\"MÁY\",\"lic_method\":99}]\n");Assert.AreEqual("MÁY",r.Registrations.Single().FeatureId);Assert.AreEqual(99,r.Registrations.Single().LicenseMethodCode);}
 }
 [TestClass] public class ClassificationTests {
  [DataTestMethod][DataRow(0,"Unknown")][DataRow(1,"Network")][DataRow(2,"StandaloneLegacy")][DataRow(3,"StandaloneDeploymentLegacy")][DataRow(4,"UserLicensing")][DataRow(99,"Unknown")] public void Maps(int c,string e)=>Assert.AreEqual(e,AutodeskLicenseMethodClassifier.Classify(c));
  [TestMethod] public void NeverInfersLicensed(){Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,AutodeskLicenseMethodClassifier.Status(4));Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,AutodeskLicenseMethodClassifier.Status(1));Assert.AreEqual(LicenseStatus.Unknown,AutodeskLicenseMethodClassifier.Status(2));}
  [TestMethod] public void UniqueYearMatchesAmbiguousDoesNot(){var r=new AutodeskRegistration{SelectedProductVersion="2025.0.0.F"};var a=new[]{new AutodeskInstallation{ProductName="AutoCAD 2025",Version="2025"}};Assert.IsNotNull(AutodeskProductMatcher.Match(r,a));Assert.IsNull(AutodeskProductMatcher.Match(r,a.Concat(new[]{new AutodeskInstallation{ProductName="Revit 2025",Version="2025"}})));}
 }
 [TestClass] public class ProviderTests {
  [TestMethod] public async Task OnlyListIsExpressible(){var x=new FakeRunner{Result=new ProcessExecutionResult{ExitCode=0,StandardOutput="[]"}};var r=await new AutodeskLicensingEvidenceProvider(x,new FakeLocator(true),new AdskLicensingListParser()).ListAsync(CancellationToken.None);Assert.IsTrue(r.Successful);Assert.AreEqual("list",x.Request.Arguments);Assert.IsTrue(x.Request.CreateNoWindow);Assert.AreEqual(TimeSpan.FromSeconds(30),x.Request.Timeout);}
  [DataTestMethod][DataRow(true,false,0,"timed out")][DataRow(false,true,0,"could not start")][DataRow(false,false,5,"non-zero")] public async Task FailuresStructured(bool t,bool s,int e,string w){var x=new FakeRunner{Result=new ProcessExecutionResult{TimedOut=t,StartFailure=s,ExitCode=e}};var r=await new AutodeskLicensingEvidenceProvider(x,new FakeLocator(true),new AdskLicensingListParser()).ListAsync(CancellationToken.None);StringAssert.Contains(r.Warnings.Single(),w);}
  [TestMethod] public async Task MissingDoesNotRun(){var x=new FakeRunner();var r=await new AutodeskLicensingEvidenceProvider(x,new FakeLocator(false),new AdskLicensingListParser()).ListAsync(CancellationToken.None);Assert.IsNull(x.Request);Assert.IsFalse(r.Successful);}
 }
 [TestClass] public class ScannerTests {
  [TestMethod] public async Task OneConservativeResultPerProduct(){var i=new[]{new AutodeskInstallation{ProductName="Autodesk AutoCAD 2025",Version="2025"},new AutodeskInstallation{ProductName="Autodesk Revit 2024",Version="2024"}};var g=new[]{new AutodeskRegistration{FeatureId="ACD",SelectedProductVersion="2025.0.0.F",LicenseMethodCode=4}};var r=await new AutodeskLicenseScanner(new FakeDetector(i),new FakeEvidence(g),new FakeService(true,true)).ScanAsync(Ctx(),CancellationToken.None);Assert.AreEqual(2,r.Count);Assert.IsTrue(r.All(x=>x.ScannerId=="autodesk.desktop"&&x.IsLicensed==null));Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single(x=>x.ProductName.Contains("AutoCAD")).Status);Assert.AreEqual(LicenseStatus.Unknown,r.Single(x=>x.ProductName.Contains("Revit")).Status);}
  [TestMethod] public async Task NoDataEmpty(){var r=await Scan(Array.Empty<AutodeskInstallation>(),Array.Empty<AutodeskRegistration>(),false);Assert.AreEqual(0,r.Count);}
  [TestMethod] public async Task OrphanRegistrationNotLicensed(){var r=await Scan(Array.Empty<AutodeskInstallation>(),new[]{new AutodeskRegistration{FeatureId="RVT",LicenseMethodCode=1}},true);Assert.IsFalse(r.Single().Installed);Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single().Status);}
  [TestMethod] public async Task RunningServiceNotLicensed(){var r=await Scan(new[]{new AutodeskInstallation{ProductName="Autodesk Maya"}},Array.Empty<AutodeskRegistration>(),true);Assert.AreEqual(LicenseStatus.Unknown,r.Single().Status);}
  [TestMethod] public async Task Cancellation(){var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsExceptionAsync<OperationCanceledException>(()=>new AutodeskLicenseScanner(new FakeDetector(Array.Empty<AutodeskInstallation>()),new FakeEvidence(Array.Empty<AutodeskRegistration>()),new FakeService(false,false)).ScanAsync(Ctx(),c.Token));}
  static Task<IReadOnlyList<LicenseResult>> Scan(IReadOnlyList<AutodeskInstallation> i,IReadOnlyList<AutodeskRegistration> r,bool running)=>new AutodeskLicenseScanner(new FakeDetector(i),new FakeEvidence(r),new FakeService(true,running)).ScanAsync(Ctx(),CancellationToken.None); static SystemContext Ctx()=>new SystemContext{OsName="Windows"};
 }
 class FakeRunner:IProcessRunner{public ProcessExecutionRequest Request;public ProcessExecutionResult Result=new ProcessExecutionResult();public Task<ProcessExecutionResult> RunAsync(ProcessExecutionRequest r,CancellationToken c){Request=r;return Task.FromResult(Result);}}
 class FakeLocator:IAutodeskLicensingToolLocator{readonly bool x;public FakeLocator(bool v){x=v;}public AutodeskToolInfo Locate()=>new AutodeskToolInfo{Exists=x,Path=@"C:\official\AdskLicensingInstHelper.exe"};}
 class FakeDetector:IAutodeskInstallationDetector{readonly IReadOnlyList<AutodeskInstallation>x;public FakeDetector(IReadOnlyList<AutodeskInstallation>v){x=v;}public IReadOnlyList<AutodeskInstallation> Detect(SystemContext c,out IReadOnlyList<string>w){w=Array.Empty<string>();return x;}}
 class FakeEvidence:IAutodeskLicensingEvidenceProvider{readonly IReadOnlyList<AutodeskRegistration>x;public FakeEvidence(IReadOnlyList<AutodeskRegistration>v){x=v;}public Task<AutodeskEvidenceResult> ListAsync(CancellationToken c)=>Task.FromResult(new AutodeskEvidenceResult{Successful=true,Registrations=x});}
 class FakeService:IAutodeskServiceStatusProvider{readonly bool f,r;public FakeService(bool a,bool b){f=a;r=b;}public AutodeskServiceStatus GetStatus()=>new AutodeskServiceStatus{Found=f,Running=r};}
}
