using System;using System.Collections.Generic;using System.Linq;using System.Threading;using System.Threading.Tasks;using Microsoft.VisualStudio.TestTools.UnitTesting;using LicenseScope.Core.Models;using LicenseScope.Core.Runtime;using LicenseScope.SketchUp;using LicenseScope.SketchUp.Classification;using LicenseScope.SketchUp.Contracts;using LicenseScope.SketchUp.Detection;using LicenseScope.SketchUp.Models;
namespace LicenseScope.SketchUp.Tests
{
 [TestClass]public class DetectionTests{
  [TestMethod][DataRow("Trimble","SketchUp Pro 2026",true)][DataRow("SketchUp","SketchUp 2017",true)][DataRow("Trimble","SketchUp Viewer",false)][DataRow("Trimble","SketchUp SDK",false)][DataRow("Trimble","SketchUp Language Pack",false)][DataRow("Trimble","LayOut",false)][DataRow("Chaos","V-Ray for SketchUp",false)][DataRow("Other","SketchUp Pro 2025",false)]public void FiltersProducts(string publisher,string name,bool expected)=>Assert.AreEqual(expected,SketchUpInstallationDetector.IsProduct(publisher,name));
 }
 [TestClass]public class ClassificationTests{
  static SketchUpInstalledProduct Product(string year)=>new SketchUpInstalledProduct{ReleaseYear=year};
  [TestMethod]public void ModernInstallDefaultsSubscription(){Assert.AreEqual("Subscription",SketchUpLicenseClassifier.Type(Product("2026"),new SketchUpSubscriptionEvidence(),new SketchUpClassicEvidence()));}
  [TestMethod]public void SessionMeansSubscriptionNotLicensed(){var type=SketchUpLicenseClassifier.Type(Product("2019"),new SketchUpSubscriptionEvidence{SessionArtifactPresent=true},new SketchUpClassicEvidence());Assert.AreEqual("Subscription",type);Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,SketchUpLicenseClassifier.Status(type));}
  [TestMethod]public void ClassicArtifactNeverLicensed(){var type=SketchUpLicenseClassifier.Type(Product("2019"),new SketchUpSubscriptionEvidence(),new SketchUpClassicEvidence{ClassicArtifactPresent=true});Assert.AreEqual("ClassicSingleUser",type);Assert.AreEqual(LicenseStatus.Unknown,SketchUpLicenseClassifier.Status(type));}
  [TestMethod]public void NetworkNeedsVerification(){var type=SketchUpLicenseClassifier.Type(Product("2019"),new SketchUpSubscriptionEvidence(),new SketchUpClassicEvidence{NetworkConfigurationPresent=true});Assert.AreEqual("ClassicNetwork",type);Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,SketchUpLicenseClassifier.Status(type));}
  [TestMethod]public void LegacyInstallOnlyUnknown(){var type=SketchUpLicenseClassifier.Type(Product("2019"),new SketchUpSubscriptionEvidence(),new SketchUpClassicEvidence());Assert.AreEqual("Unknown",type);Assert.AreEqual(LicenseStatus.Unknown,SketchUpLicenseClassifier.Status(type));}
 }
 [TestClass]public class ScannerTests{
  [TestMethod]public async Task MultipleVersionsProduceSeparateStableResults(){var products=new[]{Product("SketchUp Pro 2025","2025"),Product("SketchUp Pro 2019","2019")};var scanner=new SketchUpLicenseScanner(new FakeDetector(products),new FakeSubscription(true),new FakeClassic(false,false));var r=await scanner.ScanAsync(Context(),CancellationToken.None);Assert.AreEqual(2,r.Count);Assert.IsTrue(r.All(x=>x.ScannerId=="trimble.sketchup"&&x.IsLicensed==null));Assert.AreEqual("SketchUp Pro 2019",r[0].ProductName);}
  [TestMethod]public async Task NoInstallReturnsEmpty(){var r=await new SketchUpLicenseScanner(new FakeDetector(Array.Empty<SketchUpInstalledProduct>()),new FakeSubscription(false),new FakeClassic(false,false)).ScanAsync(Context(),CancellationToken.None);Assert.AreEqual(0,r.Count);}
  [TestMethod]public async Task SessionPresenceDoesNotLicense(){var r=await Scan(new FakeSubscription(true),new FakeClassic(false,false));Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single().Status);Assert.AreNotEqual(true,r.Single().IsLicensed);}
  [TestMethod]public async Task RecentTimestampDoesNotLicense(){var r=await new SketchUpLicenseScanner(new FakeDetector(new[]{Product("SketchUp Pro 2026","2026")}),new FakeSubscription(true){Timestamp=DateTimeOffset.UtcNow},new FakeClassic(false,false)).ScanAsync(Context(),CancellationToken.None);Assert.AreNotEqual(LicenseStatus.Licensed,r.Single().Status);}
  [TestMethod]public async Task ClassicPresenceDoesNotLicense(){var r=await Scan(new FakeSubscription(false),new FakeClassic(true,false));Assert.AreEqual(LicenseStatus.Unknown,r.Single().Status);}
  [TestMethod]public async Task NetworkPresenceDoesNotLicense(){var r=await Scan(new FakeSubscription(false),new FakeClassic(true,true));Assert.AreEqual(LicenseStatus.NeedsOnlineVerification,r.Single().Status);Assert.IsFalse(string.Join("|",r.Single().Evidence.Select(x=>x.Value)).Contains("server.example"));}
  [TestMethod]public async Task ComponentEvidenceStaysOnParent(){var p=Product("SketchUp Pro 2026","2026");p.LayOutInstalled=true;p.StyleBuilderInstalled=true;var r=await new SketchUpLicenseScanner(new FakeDetector(new[]{p}),new FakeSubscription(false),new FakeClassic(false,false)).ScanAsync(Context(),CancellationToken.None);Assert.AreEqual(1,r.Count);Assert.AreEqual(2,r.Single().Evidence.Count(x=>x.Name.Contains("component")));}
  [TestMethod]public async Task EnvironmentalWarningsAreSanitized(){var r=await new SketchUpLicenseScanner(new FakeDetector(new[]{Product("SketchUp Pro 2026","2026")},"Registry denied"),new FakeSubscription(false,"profile denied"),new FakeClassic(false,false,"artifact denied")).ScanAsync(Context(),CancellationToken.None);Assert.AreEqual(3,r.Single().Warnings.Count(x=>x.Contains("denied")));}
  [TestMethod]public async Task CancellationPropagates(){var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsExceptionAsync<OperationCanceledException>(()=>new SketchUpLicenseScanner(new FakeDetector(Array.Empty<SketchUpInstalledProduct>()),new FakeSubscription(false),new FakeClassic(false,false)).ScanAsync(Context(),c.Token));}
  [TestMethod]public void ProductionOrderIsStable(){var ids=LicenseScope.Application.ProductionScannerFactory.CreateAll(new ProcessRunner(),new Clock()).Select(x=>x.ScannerId).ToArray();CollectionAssert.AreEqual(new[]{"microsoft.windows","microsoft.office","autodesk.desktop","adobe.desktop","trimble.sketchup"},ids);}
  static Task<IReadOnlyList<LicenseResult>>Scan(FakeSubscription s,FakeClassic c)=>new SketchUpLicenseScanner(new FakeDetector(new[]{Product("SketchUp Pro 2019","2019")}),s,c).ScanAsync(Context(),CancellationToken.None);static SketchUpInstalledProduct Product(string n,string y)=>new SketchUpInstalledProduct{ProductName=n,ReleaseYear=y,Version=y,DetectionSource="fixture"};static SystemContext Context()=>new SystemContext{OsName="Windows"};
 }
 class FakeDetector:ISketchUpInstallationDetector{readonly IReadOnlyList<SketchUpInstalledProduct>x;readonly string warning;public FakeDetector(IReadOnlyList<SketchUpInstalledProduct>v,string w=""){x=v;warning=w;}public IReadOnlyList<SketchUpInstalledProduct>Detect(SystemContext c,out IReadOnlyList<string>w){w=string.IsNullOrWhiteSpace(warning)?Array.Empty<string>():new[]{warning};return x;}}
 class FakeSubscription:ISketchUpSubscriptionEvidenceProvider{readonly bool present;readonly string warning;public DateTimeOffset?Timestamp;public FakeSubscription(bool p,string w=""){present=p;warning=w;}public SketchUpSubscriptionEvidence Detect(SketchUpInstalledProduct p,CancellationToken c)=>new SketchUpSubscriptionEvidence{VersionProfilePresent=present,SessionArtifactPresent=present,SessionArtifactLastWriteTime=Timestamp,Warning=warning};}
 class FakeClassic:ISketchUpClassicEvidenceProvider{readonly bool artifact,network;readonly string warning;public FakeClassic(bool a,bool n,string w=""){artifact=a;network=n;warning=w;}public SketchUpClassicEvidence Detect(SketchUpInstalledProduct p,CancellationToken c)=>new SketchUpClassicEvidence{ClassicArtifactPresent=artifact,NetworkConfigurationPresent=network,Warning=warning};}
 class Clock:LicenseScope.Core.Contracts.ISystemClock{public DateTimeOffset UtcNow=>DateTimeOffset.UtcNow;}
}
